/**
 * Pure templates for owner notifications generated by public partner and
 * investor forms. The submitted values are untrusted and are escaped here
 * before entering HTML or text mail.
 */
import { BUSINESS } from "@/lib/business";
import { escapeHtml } from "@/lib/newsletter/templates";

export type ContactNotificationKind = "partner" | "investor";

export type ContactNotification = {
  id: number | string;
  createdAt: string;
  name: string;
  email: string;
  organization: string | null;
  channel?: string | null;
  audience?: string | null;
  amountInterest?: string | null;
  experience?: string | null;
  message: string;
};

function wrap(title: string, body: string) {
  return `<!doctype html><html><body style="margin:0;background:#08050f;color:#f5f1ff;font-family:Arial,sans-serif"><div style="max-width:600px;margin:auto;padding:40px 24px"><div style="border:1px solid #39285a;background:#120b20;border-radius:14px;padding:32px"><p style="color:#a78bfa;text-transform:uppercase;letter-spacing:2px;font-size:12px">${escapeHtml(BUSINESS.name)}</p><h1 style="font-size:26px;margin:16px 0">${title}</h1>${body}<p style="color:#8f819f;font-size:12px;line-height:1.6;margin-top:32px">This is an internal notification from a public contact form. Verify the submission before sharing information or agreeing to terms. Reply-to is the submitter's address.</p></div></div></body></html>`;
}

function detailRows(contact: ContactNotification, kind: ContactNotificationKind) {
  const details = kind === "partner"
    ? [
        ["Partnership type", contact.channel],
        ["Audience", contact.audience],
      ]
    : [
        ["Capital range / interest", contact.amountInterest],
        ["Relevant experience", contact.experience],
      ];
  return details
    .filter(([, value]) => value)
    .map(([label, value]) => `<tr><td style="padding:6px 0;color:#8f819f">${escapeHtml(String(label))}</td><td style="padding:6px 0;text-align:right;color:#d8cee4">${escapeHtml(String(value ?? ""))}</td></tr>`)
    .join("");
}

export function contactNotificationTemplate(
  kind: ContactNotificationKind,
  contact: ContactNotification,
  ownerEmail: string,
) {
  const label = kind === "partner" ? "Partner / UGC inquiry" : "Investor / ROI inquiry";
  const subject = `New ${kind} inquiry — ${contact.name}`;
  const organization = contact.organization ? `\nOrganization: ${contact.organization}` : "";
  const kindDetails = kind === "partner"
    ? `Partnership type: ${contact.channel || "Not provided"}\nAudience: ${contact.audience || "Not provided"}`
    : `Capital range / interest: ${contact.amountInterest || "Not provided"}\nRelevant experience: ${contact.experience || "Not provided"}`;
  return {
    subject,
    replyTo: contact.email,
    html: wrap(
      `New ${escapeHtml(label)}`,
      `<p style="color:#c4b5d4;line-height:1.6">A new public inquiry is ready for review.</p><table style="width:100%;border-collapse:collapse;margin:16px 0;font-size:14px"><tbody><tr><td style="padding:6px 0;color:#8f819f">Name</td><td style="padding:6px 0;text-align:right;color:#d8cee4">${escapeHtml(contact.name)}</td></tr><tr><td style="padding:6px 0;color:#8f819f">Email</td><td style="padding:6px 0;text-align:right;color:#d8cee4">${escapeHtml(contact.email)}</td></tr><tr><td style="padding:6px 0;color:#8f819f">Organization</td><td style="padding:6px 0;text-align:right;color:#d8cee4">${escapeHtml(contact.organization || "Not provided")}</td></tr>${detailRows(contact, kind)}</tbody></table><div style="border:1px solid #39285a;border-radius:8px;padding:14px;color:#d8cee4;line-height:1.6;white-space:pre-wrap">${escapeHtml(contact.message)}</div><p style="color:#8f819f;font-size:12px">Notification destination: ${escapeHtml(ownerEmail)} · submission ${escapeHtml(String(contact.id))}</p>`,
    ),
    text: `${label}\n\nName: ${contact.name}\nEmail: ${contact.email}${organization}\n${kindDetails}\n\nMessage:\n${contact.message}\n\nNotification destination: ${ownerEmail}\nSubmission: ${contact.id}`,
  };
}