import { fetchJson, fetchText } from "./scrapers";
import type { NormalizedItem } from "./pipeline";

export async function fetchMathStackExchange(limit = 10): Promise<NormalizedItem[]> {
  try {
    const data = await fetchJson<any>(
      `https://api.stackexchange.com/2.3/questions?order=desc&sort=votes&site=math&filter=withbody&tagged=open-problem&pagesize=${limit}&key=`
    );
    const items: any[] = data?.items || [];
    return items.map((q: any) => ({
      source: "Math StackExchange",
      sourceType: "problem",
      title: q.title?.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">") || "Untitled",
      content: (q.body_markdown || q.body || q.title || "").replace(/<[^>]+>/g, " ").slice(0, 8000),
      url: q.link,
      tags: ["math", "open-problem", ...(q.tags || [])],
      metadata: { score: q.score, answerCount: q.answer_count, viewCount: q.view_count, domain: "math" },
      publishedAt: q.creation_date ? new Date(q.creation_date * 1000) : undefined,
    }));
  } catch {
    return [];
  }
}

export async function fetchMathOverflow(limit = 10): Promise<NormalizedItem[]> {
  try {
    const data = await fetchJson<any>(
      `https://api.stackexchange.com/2.3/questions?order=desc&sort=votes&site=mathoverflow&filter=withbody&tagged=open-problems&pagesize=${limit}&key=`
    );
    const items: any[] = data?.items || [];
    return items.map((q: any) => ({
      source: "MathOverflow",
      sourceType: "problem",
      title: q.title?.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">") || "Untitled",
      content: (q.body_markdown || q.body || q.title || "").replace(/<[^>]+>/g, " ").slice(0, 8000),
      url: q.link,
      tags: ["math", "open-problems", "research", ...(q.tags || [])],
      metadata: { score: q.score, answerCount: q.answer_count, domain: "math" },
      publishedAt: q.creation_date ? new Date(q.creation_date * 1000) : undefined,
    }));
  } catch {
    return [];
  }
}

export async function fetchProjectEuler(): Promise<NormalizedItem[]> {
  const EULER_PROBLEMS = [
    { id: 1, title: "Multiples of 3 or 5", content: "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.", difficulty: 5 },
    { id: 2, title: "Even Fibonacci Numbers", content: "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89. By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.", difficulty: 5 },
    { id: 3, title: "Largest Prime Factor", content: "The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 600851475143?", difficulty: 5 },
    { id: 4, title: "Largest Palindrome Product", content: "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. Find the largest palindrome made from the product of two 3-digit numbers.", difficulty: 5 },
    { id: 7, title: "10001st Prime", content: "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. What is the 10 001st prime number?", difficulty: 5 },
    { id: 10, title: "Summation of Primes", content: "The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17. Find the sum of all the primes below two million.", difficulty: 5 },
    { id: 14, title: "Longest Collatz Sequence", content: "The following iterative sequence is defined for the set of positive integers: n → n/2 (n is even); n → 3n + 1 (n is odd). Using the rule above and starting with 13, we generate the following sequence: 13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1. Which starting number, under one million, produces the longest chain?", difficulty: 5 },
    { id: 67, title: "Maximum Path Sum II", content: "By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23. Find the maximum total from top to bottom in triangle.txt, a 15K text file containing a triangle with one-hundred rows.", difficulty: 20 },
  ];

  return EULER_PROBLEMS.map(p => ({
    source: "Project Euler",
    sourceType: "problem",
    title: `Problem ${p.id}: ${p.title}`,
    content: p.content,
    url: `https://projecteuler.net/problem=${p.id}`,
    tags: ["math", "algorithm", "programming", "euler"],
    metadata: { problemId: p.id, difficulty: p.difficulty, domain: "math" },
  }));
}

export async function fetchPhysicsStackExchange(limit = 10): Promise<NormalizedItem[]> {
  try {
    const data = await fetchJson<any>(
      `https://api.stackexchange.com/2.3/questions?order=desc&sort=votes&site=physics&filter=withbody&tagged=open-problems&pagesize=${limit}&key=`
    );
    const items: any[] = data?.items || [];
    return items.map((q: any) => ({
      source: "Physics StackExchange",
      sourceType: "problem",
      title: q.title?.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">") || "Untitled",
      content: (q.body_markdown || q.body || q.title || "").replace(/<[^>]+>/g, " ").slice(0, 8000),
      url: q.link,
      tags: ["physics", "open-problems", ...(q.tags || [])],
      metadata: { score: q.score, answerCount: q.answer_count, domain: "physics" },
      publishedAt: q.creation_date ? new Date(q.creation_date * 1000) : undefined,
    }));
  } catch {
    return [];
  }
}

export async function fetchPhysicsOverflow(limit = 10): Promise<NormalizedItem[]> {
  try {
    const data = await fetchJson<any>(
      `https://physicsoverflow.org/api/questions?filter=open&limit=${limit}`
    );
    if (!data || !Array.isArray(data.questions)) return [];
    return data.questions.map((q: any) => ({
      source: "PhysicsOverflow",
      sourceType: "problem",
      title: q.title || "Untitled",
      content: (q.body || q.description || q.title || "").slice(0, 8000),
      url: q.url || `https://physicsoverflow.org/q/${q.id}`,
      tags: ["physics", "research", ...(q.tags || [])],
      metadata: { domain: "physics" },
    }));
  } catch {
    return [];
  }
}

export async function fetchGitHubTrendingIssues(limit = 10): Promise<NormalizedItem[]> {
  try {
    const data = await fetchJson<any>(
      `https://api.github.com/search/issues?q=label%3A%22help+wanted%22+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22&sort=comments&order=desc&per_page=${limit}`,
      { "Accept": "application/vnd.github.v3+json", "User-Agent": "Tessera-Bot/1.0" }
    );
    const items: any[] = data?.items || [];
    return items.map((issue: any) => ({
      source: "GitHub Issues",
      sourceType: "problem",
      title: issue.title || "Untitled Issue",
      content: (issue.body || issue.title || "").slice(0, 8000),
      url: issue.html_url,
      tags: ["code-boundary", "github", "open-source", "help-wanted", ...(issue.labels?.map((l: any) => l.name) || [])],
      metadata: { repo: issue.repository_url?.split("/").slice(-2).join("/"), comments: issue.comments, reactions: issue.reactions?.total_count, domain: "code-boundary" },
      publishedAt: issue.created_at ? new Date(issue.created_at) : undefined,
    }));
  } catch {
    return [];
  }
}

export async function fetchStackOverflowUnanswered(limit = 10): Promise<NormalizedItem[]> {
  try {
    const data = await fetchJson<any>(
      `https://api.stackexchange.com/2.3/questions?order=desc&sort=votes&site=stackoverflow&filter=withbody&tagged=algorithms;mathematics&pagesize=${limit}&answers=0&key=`
    );
    const items: any[] = data?.items || [];
    return items.map((q: any) => ({
      source: "StackOverflow Unanswered",
      sourceType: "problem",
      title: q.title?.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">") || "Untitled",
      content: (q.body_markdown || q.body || q.title || "").replace(/<[^>]+>/g, " ").slice(0, 8000),
      url: q.link,
      tags: ["code-boundary", "algorithms", ...(q.tags || [])],
      metadata: { score: q.score, viewCount: q.view_count, domain: "code-boundary" },
      publishedAt: q.creation_date ? new Date(q.creation_date * 1000) : undefined,
    }));
  } catch {
    return [];
  }
}

export async function fetchClayMillenniumProblems(): Promise<NormalizedItem[]> {
  const CLAY_PROBLEMS = [
    {
      id: "P-vs-NP",
      title: "P versus NP Problem",
      content: "The P versus NP problem asks whether every problem whose solution can be quickly verified can also be quickly solved. Formally, can every problem in NP be solved in polynomial time? This is considered the most important open problem in computer science and mathematics. A solution would have profound implications for cryptography, optimization, and artificial intelligence.",
      domain: "math",
      tags: ["clay-institute", "P-vs-NP", "complexity-theory", "open-problem"],
    },
    {
      id: "riemann-hypothesis",
      title: "Riemann Hypothesis",
      content: "The Riemann Hypothesis proposes that all non-trivial zeros of the Riemann zeta function have real part equal to 1/2. Proven results about prime distribution depend on this hypothesis. It has been verified for trillions of zeros computationally but remains unproven. A proof would revolutionize number theory and prime distribution analysis.",
      domain: "math",
      tags: ["clay-institute", "riemann", "number-theory", "open-problem"],
    },
    {
      id: "navier-stokes",
      title: "Navier-Stokes Existence and Smoothness",
      content: "The Navier-Stokes equations describe fluid flow. The millennium problem asks whether smooth solutions always exist for these equations in three dimensions, or whether singularities (turbulence breakdowns) can form. Understanding this would advance fluid dynamics, weather prediction, and turbulence theory.",
      domain: "physics",
      tags: ["clay-institute", "navier-stokes", "fluid-dynamics", "open-problem"],
    },
    {
      id: "yang-mills",
      title: "Yang-Mills Existence and Mass Gap",
      content: "Yang-Mills theory is the foundation of the Standard Model of particle physics. The millennium problem asks to prove that Yang-Mills theory exists and has a mass gap — meaning the smallest particle must have positive mass. A proof would mathematically justify quantum field theory.",
      domain: "physics",
      tags: ["clay-institute", "yang-mills", "quantum-field-theory", "open-problem"],
    },
    {
      id: "hodge-conjecture",
      title: "Hodge Conjecture",
      content: "The Hodge conjecture relates algebraic cycles (geometric shapes defined by polynomial equations) to topological cycles in complex manifolds. It predicts that certain topological patterns in algebraic varieties can be expressed as algebraic objects. This bridges algebraic geometry and topology.",
      domain: "math",
      tags: ["clay-institute", "hodge", "algebraic-geometry", "open-problem"],
    },
    {
      id: "birch-swinnerton-dyer",
      title: "Birch and Swinnerton-Dyer Conjecture",
      content: "The BSD conjecture concerns elliptic curves — cubic equations. It predicts that the rank of an elliptic curve's rational points is equal to the order of the zero of its associated L-function at s=1. This connects number theory, analysis, and arithmetic geometry.",
      domain: "math",
      tags: ["clay-institute", "elliptic-curves", "number-theory", "open-problem"],
    },
  ];

  return CLAY_PROBLEMS.map(p => ({
    source: "Clay Mathematics Institute",
    sourceType: "problem",
    title: p.title,
    content: p.content,
    url: `https://www.claymath.org/millennium-problems/${p.id}/`,
    tags: p.tags,
    metadata: { domain: p.domain, difficulty: "millennium", prizeUSD: 1000000 },
  }));
}
