import { logger } from "./logger";
import { storeMemory, searchMemory, logDecision } from "./vector-memory";
import { solveProblem } from "./problem-solver";

export interface MLDomain {
  id: number;
  name: string;
  category: string;
  description: string;
  coreConcepts: string[];
  trainingQuestions: Array<{ q: string; keywords: string[] }>;
}

export const ML_DOMAINS: MLDomain[] = [
  { id: 1, name: "Customer Churn Prediction", category: "Tabular & Structured", description: "Predict which customers will leave a service using historical behavioral data, engagement metrics, and demographic features.", coreConcepts: ["logistic regression", "random forest", "feature engineering", "class imbalance", "ROC-AUC"], trainingQuestions: [{ q: "How do you handle class imbalance in churn prediction?", keywords: ["SMOTE", "oversampling", "undersampling", "class weight"] }, { q: "What features are most predictive of customer churn?", keywords: ["engagement", "tenure", "usage", "complaints"] }] },
  { id: 2, name: "Credit Risk Prediction", category: "Tabular & Structured", description: "Assess the probability of loan default using financial history, credit scores, and economic indicators.", coreConcepts: ["gradient boosting", "feature importance", "Shapley values", "credit scoring", "Basel accords"], trainingQuestions: [{ q: "What is the difference between PD, LGD, and EAD in credit risk?", keywords: ["probability of default", "loss given default", "exposure at default"] }, { q: "How do you validate a credit risk model?", keywords: ["KS statistic", "Gini coefficient", "backtesting", "discrimination"] }] },
  { id: 3, name: "House Price Regression", category: "Tabular & Structured", description: "Predict real estate prices from property features, location data, and market conditions.", coreConcepts: ["linear regression", "regularization", "feature scaling", "spatial features", "hedonic pricing"], trainingQuestions: [{ q: "Why is location the most important feature in house price prediction?", keywords: ["spatial", "neighborhood", "amenities", "commute"] }] },
  { id: 4, name: "Employee Attrition", category: "Tabular & Structured", description: "Predict employee turnover using HR data, satisfaction surveys, and performance metrics.", coreConcepts: ["survival analysis", "Cox regression", "hazard rate", "retention modeling"], trainingQuestions: [{ q: "What HR features predict employee attrition?", keywords: ["satisfaction", "salary", "promotion", "overtime", "tenure"] }] },
  { id: 5, name: "Fraud Detection", category: "Tabular & Structured", description: "Identify fraudulent transactions in real-time using behavioral patterns and anomaly detection.", coreConcepts: ["anomaly detection", "isolation forest", "autoencoder", "real-time scoring", "false positive rate"], trainingQuestions: [{ q: "Why is fraud detection extremely imbalanced?", keywords: ["rare event", "0.1%", "precision", "recall", "cost-sensitive"] }] },
  { id: 6, name: "Insurance Claim Prediction", category: "Tabular & Structured", description: "Model insurance claim frequency and severity using policyholder and risk characteristics.", coreConcepts: ["Poisson regression", "GLM", "Tweedie distribution", "actuarial science"], trainingQuestions: [{ q: "What distributions model insurance claim severity?", keywords: ["gamma", "lognormal", "Pareto", "heavy-tailed"] }] },
  { id: 7, name: "Student Performance", category: "Tabular & Structured", description: "Predict academic outcomes and dropout risk from learning analytics and demographic data.", coreConcepts: ["educational data mining", "learning analytics", "early warning systems"], trainingQuestions: [{ q: "What features predict student dropout?", keywords: ["attendance", "grades", "engagement", "socioeconomic"] }] },
  { id: 8, name: "Sales Forecasting", category: "Tabular & Structured", description: "Predict future sales using time series decomposition, seasonality, and external factors.", coreConcepts: ["ARIMA", "Prophet", "seasonality", "trend decomposition", "exogenous variables"], trainingQuestions: [{ q: "How does Prophet handle seasonality?", keywords: ["Fourier", "additive", "multiplicative", "changepoint"] }] },
  { id: 9, name: "Inventory Demand", category: "Tabular & Structured", description: "Optimize inventory levels by predicting demand patterns and lead times.", coreConcepts: ["demand forecasting", "safety stock", "lead time", "bullwhip effect"], trainingQuestions: [{ q: "What is the bullwhip effect in supply chains?", keywords: ["amplification", "demand", "upstream", "variance"] }] },
  { id: 10, name: "Patient Readmission", category: "Tabular & Structured", description: "Predict 30-day hospital readmission risk from clinical data and social determinants.", coreConcepts: ["clinical NLP", "ICD codes", "LACE index", "risk stratification"], trainingQuestions: [{ q: "What is the LACE index for readmission?", keywords: ["length of stay", "acuity", "comorbidities", "emergency visits"] }] },

  { id: 11, name: "Image Classification", category: "Computer Vision", description: "Classify images into categories using convolutional neural networks and transfer learning.", coreConcepts: ["CNN", "ResNet", "transfer learning", "data augmentation", "batch normalization"], trainingQuestions: [{ q: "How does transfer learning work for image classification?", keywords: ["pretrained", "fine-tuning", "feature extraction", "ImageNet"] }] },
  { id: 12, name: "Object Detection", category: "Computer Vision", description: "Locate and classify objects in images using anchor boxes and region proposals.", coreConcepts: ["YOLO", "SSD", "Faster R-CNN", "anchor boxes", "NMS", "IoU"], trainingQuestions: [{ q: "How does YOLO achieve real-time object detection?", keywords: ["single pass", "grid", "bounding box", "confidence"] }] },
  { id: 13, name: "Semantic Segmentation", category: "Computer Vision", description: "Label every pixel in an image with its class using encoder-decoder architectures.", coreConcepts: ["U-Net", "FCN", "dilated convolution", "skip connections"], trainingQuestions: [{ q: "Why are skip connections important in U-Net?", keywords: ["spatial", "resolution", "context", "localization"] }] },
  { id: 14, name: "Instance Segmentation", category: "Computer Vision", description: "Detect and segment individual object instances with pixel-level masks.", coreConcepts: ["Mask R-CNN", "panoptic segmentation", "instance masks"], trainingQuestions: [{ q: "How does Mask R-CNN extend Faster R-CNN?", keywords: ["mask branch", "pixel-level", "parallel", "RoIAlign"] }] },
  { id: 15, name: "Facial Recognition", category: "Computer Vision", description: "Identify and verify faces using metric learning and embedding spaces.", coreConcepts: ["FaceNet", "triplet loss", "ArcFace", "face embedding", "liveness detection"], trainingQuestions: [{ q: "What is triplet loss in face recognition?", keywords: ["anchor", "positive", "negative", "margin", "embedding"] }] },
  { id: 16, name: "Medical Image Analysis", category: "Computer Vision", description: "Diagnose conditions from X-rays, MRIs, and CT scans using deep learning.", coreConcepts: ["radiomics", "3D convolution", "attention maps", "Grad-CAM"], trainingQuestions: [{ q: "How does Grad-CAM explain CNN predictions?", keywords: ["gradient", "activation", "heatmap", "interpretability"] }] },
  { id: 17, name: "Satellite Imagery", category: "Computer Vision", description: "Analyze aerial and satellite images for land use, change detection, and environmental monitoring.", coreConcepts: ["remote sensing", "multispectral", "change detection", "GIS"], trainingQuestions: [{ q: "What spectral bands are useful for vegetation analysis?", keywords: ["NDVI", "near-infrared", "red", "chlorophyll"] }] },
  { id: 18, name: "Autonomous Driving", category: "Computer Vision", description: "Detect lanes, signs, and pedestrians for self-driving vehicle perception.", coreConcepts: ["LiDAR", "sensor fusion", "3D detection", "bird's eye view"], trainingQuestions: [{ q: "How does sensor fusion combine camera and LiDAR?", keywords: ["point cloud", "projection", "depth", "multimodal"] }] },
  { id: 19, name: "Fashion Recognition", category: "Computer Vision", description: "Classify clothing items and provide visual similarity recommendations.", coreConcepts: ["visual similarity", "attribute prediction", "style embedding"], trainingQuestions: [{ q: "How do visual embeddings enable fashion recommendation?", keywords: ["similarity", "feature vector", "nearest neighbor", "style"] }] },
  { id: 20, name: "Plant Disease Detection", category: "Computer Vision", description: "Identify crop diseases from leaf images using mobile-friendly CNN models.", coreConcepts: ["MobileNet", "edge deployment", "data augmentation", "PlantVillage"], trainingQuestions: [{ q: "Why is data augmentation critical for plant disease models?", keywords: ["limited data", "rotation", "color jitter", "generalization"] }] },

  { id: 21, name: "Text Classification", category: "NLP", description: "Classify text into categories: sentiment, spam, topic, intent using transformers.", coreConcepts: ["BERT", "fine-tuning", "tokenization", "attention mechanism", "embedding"], trainingQuestions: [{ q: "How does BERT's attention mechanism work?", keywords: ["self-attention", "query", "key", "value", "multi-head"] }] },
  { id: 22, name: "Named Entity Recognition", category: "NLP", description: "Extract entities (persons, organizations, locations) from unstructured text.", coreConcepts: ["BIO tagging", "CRF", "SpaCy", "sequence labeling"], trainingQuestions: [{ q: "What is BIO tagging in NER?", keywords: ["beginning", "inside", "outside", "entity boundary"] }] },
  { id: 23, name: "Machine Translation", category: "NLP", description: "Translate between languages using sequence-to-sequence models with attention.", coreConcepts: ["seq2seq", "attention", "beam search", "BLEU score", "transformer"], trainingQuestions: [{ q: "Why did transformers replace RNNs for translation?", keywords: ["parallelization", "long-range", "self-attention", "positional"] }] },
  { id: 24, name: "Question Answering", category: "NLP", description: "Extract or generate answers from context passages or knowledge bases.", coreConcepts: ["extractive QA", "generative QA", "SQuAD", "retrieval-augmented"], trainingQuestions: [{ q: "What is retrieval-augmented generation (RAG)?", keywords: ["retrieve", "generate", "context", "knowledge base"] }] },
  { id: 25, name: "Text Summarization", category: "NLP", description: "Condense documents into concise summaries preserving key information.", coreConcepts: ["extractive", "abstractive", "ROUGE score", "T5", "PEGASUS"], trainingQuestions: [{ q: "What is the difference between extractive and abstractive summarization?", keywords: ["select sentences", "generate new", "paraphrase", "compression"] }] },
  { id: 26, name: "Conversational AI", category: "NLP", description: "Build chatbots and dialogue systems with context management and intent detection.", coreConcepts: ["dialogue state", "intent classification", "slot filling", "RLHF"], trainingQuestions: [{ q: "How does RLHF improve conversational AI?", keywords: ["human feedback", "reward model", "preference", "alignment"] }] },
  { id: 27, name: "Fake News Detection", category: "NLP", description: "Identify misinformation using linguistic features, source credibility, and propagation patterns.", coreConcepts: ["stance detection", "claim verification", "fact-checking", "propaganda"], trainingQuestions: [{ q: "What features indicate fake news?", keywords: ["emotional language", "source credibility", "propagation", "sensational"] }] },
  { id: 28, name: "Hate Speech Detection", category: "NLP", description: "Detect toxic, hateful, and harmful content using NLP classifiers.", coreConcepts: ["toxicity scoring", "context-dependent", "implicit hate", "multilingual"], trainingQuestions: [{ q: "Why is context important in hate speech detection?", keywords: ["reclaimed language", "sarcasm", "in-group", "implicit"] }] },
  { id: 29, name: "Document Classification", category: "NLP", description: "Categorize legal, medical, and business documents by type and content.", coreConcepts: ["document embedding", "hierarchical attention", "domain-specific"], trainingQuestions: [{ q: "How do domain-specific language models improve document classification?", keywords: ["pretraining", "domain corpus", "vocabulary", "fine-tune"] }] },
  { id: 30, name: "Grammar Correction", category: "NLP", description: "Detect and correct grammatical errors using sequence-to-sequence models.", coreConcepts: ["error detection", "GEC", "T5", "edit distance"], trainingQuestions: [{ q: "How does T5 approach grammar correction?", keywords: ["text-to-text", "corrupted input", "denoising", "span corruption"] }] },

  { id: 31, name: "Stock Price Prediction", category: "Time Series", description: "Forecast equity prices using technical indicators, fundamentals, and sentiment.", coreConcepts: ["LSTM", "technical indicators", "efficient market hypothesis", "alpha"], trainingQuestions: [{ q: "Why is stock prediction fundamentally difficult?", keywords: ["efficient market", "random walk", "noise", "non-stationary"] }] },
  { id: 32, name: "Energy Forecasting", category: "Time Series", description: "Predict energy consumption and generation for grid optimization.", coreConcepts: ["load forecasting", "renewable intermittency", "smart grid", "peak demand"], trainingQuestions: [{ q: "How do weather patterns affect energy forecasting?", keywords: ["solar irradiance", "wind speed", "temperature", "demand correlation"] }] },
  { id: 33, name: "Weather Forecasting", category: "Time Series", description: "Predict weather conditions using numerical models and ML post-processing.", coreConcepts: ["NWP", "ensemble methods", "downscaling", "FourCastNet"], trainingQuestions: [{ q: "How does ML complement numerical weather prediction?", keywords: ["post-processing", "bias correction", "downscaling", "speed"] }] },
  { id: 34, name: "Traffic Flow Prediction", category: "Time Series", description: "Forecast traffic volumes and travel times using spatiotemporal graph networks.", coreConcepts: ["graph neural network", "spatiotemporal", "adjacency matrix"], trainingQuestions: [{ q: "Why are graph neural networks used for traffic?", keywords: ["road network", "spatial dependency", "temporal", "graph convolution"] }] },
  { id: 35, name: "Anomaly Detection", category: "Time Series", description: "Detect unusual patterns in sensor data, logs, and monitoring systems.", coreConcepts: ["isolation forest", "autoencoder", "statistical process control"], trainingQuestions: [{ q: "How do autoencoders detect anomalies?", keywords: ["reconstruction error", "normal distribution", "threshold", "latent space"] }] },
  { id: 36, name: "Speech Recognition", category: "Time Series", description: "Convert spoken language to text using end-to-end neural models.", coreConcepts: ["Whisper", "CTC loss", "beam search", "mel spectrogram"], trainingQuestions: [{ q: "How does CTC loss handle variable-length alignment?", keywords: ["blank token", "monotonic", "marginalization", "alignment-free"] }] },
  { id: 37, name: "Music Generation", category: "Time Series", description: "Generate music using recurrent models, transformers, and diffusion.", coreConcepts: ["MIDI representation", "Music Transformer", "MuseNet", "audio diffusion"], trainingQuestions: [{ q: "How do transformers model musical structure?", keywords: ["relative attention", "long-range", "harmony", "melody"] }] },
  { id: 38, name: "Video Action Recognition", category: "Time Series", description: "Classify human actions in video using 3D convolutions and temporal modeling.", coreConcepts: ["3D CNN", "temporal segment", "I3D", "SlowFast"], trainingQuestions: [{ q: "How does SlowFast process video at two speeds?", keywords: ["slow pathway", "fast pathway", "spatial", "temporal resolution"] }] },
  { id: 39, name: "Human Activity Recognition", category: "Time Series", description: "Classify activities from wearable sensor data (accelerometer, gyroscope).", coreConcepts: ["IMU sensors", "sliding window", "feature extraction", "1D CNN"], trainingQuestions: [{ q: "What sensor features distinguish walking from running?", keywords: ["acceleration magnitude", "frequency", "stride", "periodicity"] }] },
  { id: 40, name: "Crypto Price Forecasting", category: "Time Series", description: "Predict cryptocurrency prices using on-chain metrics and market sentiment.", coreConcepts: ["on-chain analysis", "MVRV ratio", "social sentiment", "volatility"], trainingQuestions: [{ q: "What on-chain metrics predict crypto price movements?", keywords: ["active addresses", "hash rate", "exchange flows", "HODL waves"] }] },

  { id: 41, name: "Movie Recommendation", category: "Recommendation", description: "Recommend movies using collaborative filtering and content-based methods.", coreConcepts: ["collaborative filtering", "matrix factorization", "content-based", "hybrid"], trainingQuestions: [{ q: "How does matrix factorization work for recommendations?", keywords: ["latent factors", "SVD", "user-item", "embedding"] }] },
  { id: 42, name: "Product Recommendation", category: "Recommendation", description: "E-commerce product recommendations using purchase history and browsing behavior.", coreConcepts: ["association rules", "session-based", "deep learning recommender"], trainingQuestions: [{ q: "What is the cold start problem in recommendations?", keywords: ["new user", "new item", "no history", "content-based fallback"] }] },
  { id: 43, name: "Music Recommendation", category: "Recommendation", description: "Recommend songs and playlists using audio features and listening patterns.", coreConcepts: ["audio embedding", "playlist continuation", "mood detection"], trainingQuestions: [{ q: "How does Spotify's Discover Weekly work?", keywords: ["collaborative", "audio features", "taste profile", "exploration"] }] },
  { id: 44, name: "News Recommendation", category: "Recommendation", description: "Personalize news feeds while avoiding filter bubbles and promoting diversity.", coreConcepts: ["recency bias", "filter bubble", "diversity-aware", "click prediction"], trainingQuestions: [{ q: "What is the filter bubble problem in news recommendation?", keywords: ["echo chamber", "polarization", "diversity", "serendipity"] }] },
  { id: 45, name: "Job Matching", category: "Recommendation", description: "Match candidates to jobs using skill extraction and semantic similarity.", coreConcepts: ["skill taxonomy", "semantic matching", "two-sided marketplace"], trainingQuestions: [{ q: "How do you handle skill synonyms in job matching?", keywords: ["embedding", "taxonomy", "normalization", "ESCO"] }] },
  { id: 46, name: "Social Connection", category: "Recommendation", description: "Recommend friends and connections in social networks using graph features.", coreConcepts: ["graph embedding", "common neighbors", "triadic closure"], trainingQuestions: [{ q: "What is triadic closure in social networks?", keywords: ["mutual friends", "triangle", "transitivity", "strong ties"] }] },
  { id: 47, name: "Restaurant Recommendation", category: "Recommendation", description: "Recommend restaurants using location, preferences, reviews, and context.", coreConcepts: ["geospatial features", "review sentiment", "context-aware"], trainingQuestions: [{ q: "How does context affect restaurant recommendations?", keywords: ["time of day", "weather", "occasion", "companion"] }] },
  { id: 48, name: "Video Recommendation", category: "Recommendation", description: "Recommend videos using engagement signals, watch history, and content features.", coreConcepts: ["two-tower model", "watch time prediction", "engagement optimization"], trainingQuestions: [{ q: "How does YouTube's recommendation system work?", keywords: ["candidate generation", "ranking", "watch time", "diversity"] }] },
  { id: 49, name: "Personalized Advertising", category: "Recommendation", description: "Target ads using user profiles, behavior, and contextual signals.", coreConcepts: ["CTR prediction", "bid optimization", "lookalike audiences"], trainingQuestions: [{ q: "How does click-through rate prediction work?", keywords: ["feature interaction", "deep&wide", "user embedding", "ad embedding"] }] },
  { id: 50, name: "Learning Path Recommendation", category: "Recommendation", description: "Recommend courses and learning materials based on knowledge gaps and goals.", coreConcepts: ["knowledge tracing", "prerequisite graph", "adaptive learning"], trainingQuestions: [{ q: "What is knowledge tracing in educational AI?", keywords: ["student model", "mastery probability", "BKT", "deep knowledge tracing"] }] },

  { id: 51, name: "Speaker Identification", category: "Audio", description: "Identify who is speaking using voice biometrics and speaker embeddings.", coreConcepts: ["d-vector", "x-vector", "speaker embedding", "verification vs identification"], trainingQuestions: [{ q: "What is the difference between speaker verification and identification?", keywords: ["one-to-one", "one-to-many", "threshold", "enrollment"] }] },
  { id: 52, name: "Music Genre Classification", category: "Audio", description: "Classify music by genre using audio features and spectrograms.", coreConcepts: ["MFCC", "mel spectrogram", "chroma features", "tempo"], trainingQuestions: [{ q: "What are MFCCs and why are they used in audio ML?", keywords: ["mel frequency", "cepstral", "human perception", "filterbank"] }] },
  { id: 53, name: "Voice Emotion Detection", category: "Audio", description: "Detect emotions from speech using prosodic and spectral features.", coreConcepts: ["prosody", "pitch", "energy", "speaking rate", "valence-arousal"], trainingQuestions: [{ q: "What acoustic features indicate emotional state?", keywords: ["pitch variation", "energy", "speaking rate", "formants"] }] },
  { id: 54, name: "Sound Event Detection", category: "Audio", description: "Detect and classify environmental sounds (sirens, glass breaking, etc.).", coreConcepts: ["AudioSet", "multi-label", "weakly supervised", "sound taxonomy"], trainingQuestions: [{ q: "How does weakly supervised learning apply to sound detection?", keywords: ["clip-level labels", "frame-level prediction", "attention pooling"] }] },
  { id: 55, name: "Speech Transcription", category: "Audio", description: "Automatic speech recognition with punctuation and speaker diarization.", coreConcepts: ["Whisper", "wav2vec", "CTC", "language model", "beam search"], trainingQuestions: [{ q: "How does Whisper achieve multilingual transcription?", keywords: ["multitask", "language token", "timestamp", "680000 hours"] }] },
  { id: 56, name: "Language Identification", category: "Audio", description: "Identify the language being spoken from audio samples.", coreConcepts: ["phonotactic", "acoustic", "i-vector", "language embedding"], trainingQuestions: [{ q: "How do phonotactic features identify language?", keywords: ["phone sequences", "n-gram", "language-specific patterns", "phoneme inventory"] }] },
  { id: 57, name: "Audio Source Separation", category: "Audio", description: "Separate mixed audio into individual sources (vocals, instruments).", coreConcepts: ["Demucs", "U-Net", "spectrogram masking", "cocktail party problem"], trainingQuestions: [{ q: "What is the cocktail party problem?", keywords: ["multiple speakers", "selective attention", "source separation", "auditory scene"] }] },
  { id: 58, name: "Beat Detection", category: "Audio", description: "Detect tempo and beat positions in music for synchronization.", coreConcepts: ["onset detection", "tempo estimation", "dynamic programming", "autocorrelation"], trainingQuestions: [{ q: "How does autocorrelation estimate tempo?", keywords: ["periodicity", "lag", "peak detection", "BPM"] }] },
  { id: 59, name: "Environmental Sound", category: "Audio", description: "Classify ambient sounds for smart environments and monitoring.", coreConcepts: ["ESC-50", "urban sound", "spectrogram CNN", "data augmentation"], trainingQuestions: [{ q: "What data augmentation techniques work for audio?", keywords: ["time stretch", "pitch shift", "noise injection", "SpecAugment"] }] },
  { id: 60, name: "Accent Recognition", category: "Audio", description: "Identify regional accents and dialects from speech patterns.", coreConcepts: ["phonetic features", "prosodic patterns", "sociolinguistics"], trainingQuestions: [{ q: "What acoustic features distinguish accents?", keywords: ["vowel space", "intonation", "rhythm", "phoneme realization"] }] },

  { id: 61, name: "Link Prediction", category: "Graphs", description: "Predict future edges in social, biological, and knowledge graphs.", coreConcepts: ["graph embedding", "node2vec", "GNN", "common neighbors", "Jaccard"], trainingQuestions: [{ q: "How does node2vec create graph embeddings?", keywords: ["random walk", "skip-gram", "BFS", "DFS", "homophily"] }] },
  { id: 62, name: "Node Classification", category: "Graphs", description: "Classify nodes in a graph using neighborhood aggregation.", coreConcepts: ["GCN", "GraphSAGE", "message passing", "semi-supervised"], trainingQuestions: [{ q: "How does message passing work in GCNs?", keywords: ["aggregate", "neighbor", "update", "layer", "feature propagation"] }] },
  { id: 63, name: "Molecular Property Prediction", category: "Graphs", description: "Predict molecular properties from graph representations of atoms and bonds.", coreConcepts: ["SMILES", "molecular graph", "message passing neural network", "SchNet"], trainingQuestions: [{ q: "How are molecules represented as graphs?", keywords: ["atoms as nodes", "bonds as edges", "features", "3D coordinates"] }] },
  { id: 64, name: "Knowledge Graph Completion", category: "Graphs", description: "Infer missing relations in knowledge graphs using embedding models.", coreConcepts: ["TransE", "RotatE", "ComplEx", "relation embedding"], trainingQuestions: [{ q: "How does TransE model knowledge graph relations?", keywords: ["head + relation = tail", "translation", "embedding space", "scoring"] }] },
  { id: 65, name: "Traffic Network Prediction", category: "Graphs", description: "Predict traffic on road networks using spatial-temporal graph models.", coreConcepts: ["STGCN", "diffusion convolution", "temporal attention"], trainingQuestions: [{ q: "Why are spatial-temporal graph networks used for traffic?", keywords: ["road topology", "temporal patterns", "diffusion", "adjacency"] }] },
  { id: 66, name: "Citation Recommendation", category: "Graphs", description: "Recommend relevant papers using citation networks and content similarity.", coreConcepts: ["citation graph", "bibliographic coupling", "co-citation"], trainingQuestions: [{ q: "How do citation networks help paper recommendation?", keywords: ["reference overlap", "co-citation", "influence spread", "PageRank"] }] },
  { id: 67, name: "Fraud Ring Detection", category: "Graphs", description: "Detect organized fraud rings in transaction and social graphs.", coreConcepts: ["community detection", "suspicious subgraph", "heterogeneous graph"], trainingQuestions: [{ q: "How do graph features reveal fraud rings?", keywords: ["clustering coefficient", "shared addresses", "temporal burst", "collusion"] }] },
  { id: 68, name: "Protein Interaction Prediction", category: "Graphs", description: "Predict protein-protein interactions from sequence and structural data.", coreConcepts: ["PPI network", "domain interaction", "evolutionary conservation"], trainingQuestions: [{ q: "What features predict protein-protein interactions?", keywords: ["co-expression", "domain pairs", "phylogenetic profile", "structural complementarity"] }] },
  { id: 69, name: "Community Detection", category: "Graphs", description: "Identify communities and clusters in complex networks.", coreConcepts: ["modularity", "Louvain", "spectral clustering", "label propagation"], trainingQuestions: [{ q: "What is modularity in community detection?", keywords: ["expected edges", "actual edges", "partition quality", "null model"] }] },
  { id: 70, name: "Graph Recommendation", category: "Graphs", description: "Build recommendations using graph structure and user-item bipartite graphs.", coreConcepts: ["bipartite graph", "PinSage", "LightGCN", "graph attention"], trainingQuestions: [{ q: "How does LightGCN simplify graph recommendations?", keywords: ["no feature transformation", "neighborhood aggregation", "layer combination", "embedding"] }] },

  { id: 71, name: "Image Captioning", category: "Multimodal", description: "Generate textual descriptions of images using vision-language models.", coreConcepts: ["encoder-decoder", "CLIP", "BLIP", "visual attention"], trainingQuestions: [{ q: "How does CLIP connect images and text?", keywords: ["contrastive learning", "image encoder", "text encoder", "cosine similarity"] }] },
  { id: 72, name: "Visual Question Answering", category: "Multimodal", description: "Answer questions about images by combining vision and language understanding.", coreConcepts: ["multimodal fusion", "cross-attention", "VQA dataset"], trainingQuestions: [{ q: "How does cross-attention fuse visual and textual features?", keywords: ["query from text", "key-value from image", "attention weights", "grounding"] }] },
  { id: 73, name: "Text-to-Image Generation", category: "Multimodal", description: "Generate images from text descriptions using diffusion models.", coreConcepts: ["Stable Diffusion", "DALL-E", "CLIP guidance", "denoising"], trainingQuestions: [{ q: "How do diffusion models generate images?", keywords: ["forward noise", "reverse denoising", "U-Net", "score matching"] }] },
  { id: 74, name: "Video Captioning", category: "Multimodal", description: "Generate descriptions of video content with temporal understanding.", coreConcepts: ["temporal attention", "frame sampling", "dense captioning"], trainingQuestions: [{ q: "How does temporal attention handle video captioning?", keywords: ["frame selection", "temporal ordering", "key frames", "motion"] }] },
  { id: 75, name: "Audio-Visual Speech Recognition", category: "Multimodal", description: "Lip-reading combined with audio for robust speech recognition.", coreConcepts: ["lip reading", "visual speech", "multimodal fusion", "noise robustness"], trainingQuestions: [{ q: "Why does adding visual information improve speech recognition?", keywords: ["lip movements", "noisy environments", "complementary", "visemes"] }] },
  { id: 76, name: "Multimodal Sentiment", category: "Multimodal", description: "Analyze sentiment from text, audio, and visual cues simultaneously.", coreConcepts: ["fusion strategies", "early/late fusion", "tensor fusion"], trainingQuestions: [{ q: "What are early vs late fusion strategies?", keywords: ["feature-level", "decision-level", "concatenation", "ensemble"] }] },
  { id: 77, name: "Zero-Shot Learning", category: "Multimodal", description: "Classify unseen categories using semantic descriptions and embeddings.", coreConcepts: ["attribute-based", "semantic embedding", "generalized zero-shot"], trainingQuestions: [{ q: "How does zero-shot learning classify unseen categories?", keywords: ["semantic description", "attribute vector", "embedding alignment", "transfer"] }] },
  { id: 78, name: "Cross-Lingual Transfer", category: "Multimodal", description: "Transfer NLP models across languages using multilingual representations.", coreConcepts: ["mBERT", "XLM-R", "language-agnostic", "alignment"], trainingQuestions: [{ q: "How does XLM-R achieve cross-lingual transfer?", keywords: ["shared vocabulary", "100 languages", "masked language model", "CommonCrawl"] }] },
  { id: 79, name: "Federated Learning", category: "Multimodal", description: "Train models across distributed devices without sharing raw data.", coreConcepts: ["FedAvg", "differential privacy", "communication efficiency"], trainingQuestions: [{ q: "How does federated learning preserve privacy?", keywords: ["local training", "gradient aggregation", "no raw data", "differential privacy"] }] },
  { id: 80, name: "Self-Supervised Learning", category: "Multimodal", description: "Learn representations from unlabeled data using pretext tasks.", coreConcepts: ["contrastive learning", "masked prediction", "BYOL", "SimCLR"], trainingQuestions: [{ q: "How does contrastive learning create useful representations?", keywords: ["positive pairs", "negative pairs", "InfoNCE", "augmentation"] }] },

  { id: 81, name: "Protein Folding", category: "Scientific", description: "Predict 3D protein structure from amino acid sequence.", coreConcepts: ["AlphaFold2", "MSA", "attention", "pairwise features", "Evoformer"], trainingQuestions: [{ q: "How did AlphaFold2 solve protein structure prediction?", keywords: ["evolutionary", "attention", "end-to-end", "structure module", "CASP14"] }] },
  { id: 82, name: "Drug Discovery", category: "Scientific", description: "Design novel drug candidates using molecular generation and property prediction.", coreConcepts: ["molecular generation", "ADMET", "virtual screening", "retrosynthesis"], trainingQuestions: [{ q: "What is virtual screening in drug discovery?", keywords: ["compound library", "docking", "binding affinity", "hit identification"] }] },
  { id: 83, name: "Climate Modeling", category: "Scientific", description: "Model climate change impacts using Earth system models and ML downscaling.", coreConcepts: ["GCM", "downscaling", "extreme events", "attribution science"], trainingQuestions: [{ q: "How does ML improve climate model resolution?", keywords: ["statistical downscaling", "super-resolution", "regional patterns", "bias correction"] }] },
  { id: 84, name: "Astronomical Classification", category: "Scientific", description: "Classify galaxies, stars, and transients from telescope surveys.", coreConcepts: ["photometric redshift", "galaxy morphology", "transient classification"], trainingQuestions: [{ q: "How do you classify galaxy morphology with ML?", keywords: ["spiral", "elliptical", "irregular", "Galaxy Zoo", "CNN"] }] },
  { id: 85, name: "Particle Physics", category: "Scientific", description: "Classify particle collision events at CERN using deep learning.", coreConcepts: ["jet classification", "event reconstruction", "calorimeter", "Monte Carlo"], trainingQuestions: [{ q: "How is deep learning used at the LHC?", keywords: ["jet tagging", "event selection", "trigger", "background rejection"] }] },
  { id: 86, name: "Genomic Classification", category: "Scientific", description: "Classify genomic sequences for variant calling and gene expression.", coreConcepts: ["k-mer features", "sequence embedding", "variant calling", "GWAS"], trainingQuestions: [{ q: "How are DNA sequences represented for ML?", keywords: ["one-hot encoding", "k-mer", "word2vec", "byte-pair encoding"] }] },
  { id: 87, name: "Battery Lifetime Prediction", category: "Scientific", description: "Predict battery degradation and remaining useful life from cycling data.", coreConcepts: ["capacity fade", "impedance", "Arrhenius", "cycle life"], trainingQuestions: [{ q: "What features predict battery degradation?", keywords: ["capacity fade", "impedance rise", "temperature", "C-rate"] }] },
  { id: 88, name: "Materials Property Prediction", category: "Scientific", description: "Predict material properties from crystal structure and composition.", coreConcepts: ["crystal graph", "band gap", "formation energy", "Materials Project"], trainingQuestions: [{ q: "How are crystal structures represented for ML?", keywords: ["crystal graph", "atom features", "bond features", "periodic boundary"] }] },
  { id: 89, name: "Earthquake Prediction", category: "Scientific", description: "Forecast seismic events using historical catalogs and precursor signals.", coreConcepts: ["Gutenberg-Richter", "aftershock", "ETAS model", "seismogram"], trainingQuestions: [{ q: "What is the Gutenberg-Richter law?", keywords: ["magnitude-frequency", "power law", "b-value", "scaling"] }] },
  { id: 90, name: "Crop Yield Prediction", category: "Scientific", description: "Forecast agricultural yields from satellite imagery, weather, and soil data.", coreConcepts: ["NDVI", "growing degree days", "soil moisture", "phenology"], trainingQuestions: [{ q: "How does NDVI indicate crop health?", keywords: ["near-infrared", "red", "vegetation index", "chlorophyll", "biomass"] }] },

  { id: 91, name: "Handwriting Recognition", category: "Creative", description: "Recognize handwritten text from images using CNN-RNN architectures.", coreConcepts: ["CRNN", "CTC", "IAM dataset", "pen stroke"], trainingQuestions: [{ q: "How does CTC handle variable-length handwriting?", keywords: ["alignment-free", "blank token", "best path", "beam search"] }] },
  { id: 92, name: "Style Transfer", category: "Creative", description: "Apply artistic styles to images using neural style transfer.", coreConcepts: ["Gram matrix", "content loss", "style loss", "perceptual loss"], trainingQuestions: [{ q: "What is a Gram matrix in style transfer?", keywords: ["feature correlation", "texture representation", "channel-wise", "inner product"] }] },
  { id: 93, name: "Game Playing AI", category: "Creative", description: "Train agents to play games using reinforcement learning and search.", coreConcepts: ["AlphaGo", "MCTS", "self-play", "policy network", "value network"], trainingQuestions: [{ q: "How does AlphaGo combine MCTS with neural networks?", keywords: ["policy network", "value network", "tree search", "self-play"] }] },
  { id: 94, name: "Robotics RL", category: "Creative", description: "Train robotic controllers using sim-to-real transfer and curriculum learning.", coreConcepts: ["sim-to-real", "domain randomization", "curriculum learning", "PPO"], trainingQuestions: [{ q: "What is sim-to-real transfer?", keywords: ["simulation", "real world", "domain gap", "randomization"] }] },
  { id: 95, name: "Meme Classification", category: "Creative", description: "Classify and understand internet memes using multimodal analysis.", coreConcepts: ["hateful memes", "multimodal reasoning", "cultural context"], trainingQuestions: [{ q: "Why is meme understanding difficult for AI?", keywords: ["cultural context", "irony", "visual-text interaction", "evolving"] }] },
  { id: 96, name: "Recipe Generation", category: "Creative", description: "Generate recipes from ingredients using conditional text generation.", coreConcepts: ["conditional generation", "ingredient embedding", "recipe graph"], trainingQuestions: [{ q: "How do you model ingredient compatibility?", keywords: ["co-occurrence", "flavor compound", "embedding similarity", "complementary"] }] },
  { id: 97, name: "Poetry Generation", category: "Creative", description: "Generate creative text with constraints on meter, rhyme, and theme.", coreConcepts: ["constrained decoding", "rhyme detection", "meter analysis", "creativity"], trainingQuestions: [{ q: "How do you enforce rhyme and meter in text generation?", keywords: ["phoneme", "stress pattern", "constrained beam search", "rejection sampling"] }] },
  { id: 98, name: "Deepfake Detection", category: "Creative", description: "Detect manipulated videos and images using forensic analysis.", coreConcepts: ["face manipulation", "frequency analysis", "biological signals"], trainingQuestions: [{ q: "What artifacts reveal deepfake videos?", keywords: ["blending boundary", "inconsistent lighting", "temporal flickering", "eye reflection"] }] },
  { id: 99, name: "Synthetic Data Generation", category: "Creative", description: "Generate realistic synthetic data for privacy-preserving ML training.", coreConcepts: ["GAN", "VAE", "differential privacy", "utility vs privacy"], trainingQuestions: [{ q: "How do GANs generate realistic synthetic data?", keywords: ["generator", "discriminator", "adversarial", "Nash equilibrium"] }] },
  { id: 100, name: "RL Portfolio Optimization", category: "Creative", description: "Optimize investment portfolios using reinforcement learning agents.", coreConcepts: ["Markowitz", "Sharpe ratio", "policy gradient", "risk-adjusted return"], trainingQuestions: [{ q: "How does RL approach portfolio optimization differently than Markowitz?", keywords: ["dynamic rebalancing", "transaction costs", "non-stationary", "sequential decision"] }] },
];

export async function trainOnMLDomains(domainIds?: number[]): Promise<{ trained: number; stored: number; errors: string[] }> {
  const domains = domainIds
    ? ML_DOMAINS.filter(d => domainIds.includes(d.id))
    : ML_DOMAINS;

  let stored = 0;
  const errors: string[] = [];

  for (const domain of domains) {
    try {
      const content = [
        `ML Domain #${domain.id}: ${domain.name}`,
        `Category: ${domain.category}`,
        `Description: ${domain.description}`,
        `Core Concepts: ${domain.coreConcepts.join(", ")}`,
        ...domain.trainingQuestions.map(q =>
          `Q: ${q.q}\nKey concepts: ${q.keywords.join(", ")}`
        ),
      ].join("\n");

      await storeMemory({
        content,
        source: "ml-training-domains",
        category: "machine-learning",
        metadata: {
          domainId: domain.id,
          domainName: domain.name,
          category: domain.category,
          coreConcepts: domain.coreConcepts,
          type: "ml-domain-knowledge",
        },
      });
      stored++;
    } catch (err) {
      errors.push(`Domain ${domain.id} (${domain.name}): ${err}`);
    }
  }

  logger.info({ trained: domains.length, stored, errors: errors.length }, "ML domain training complete");
  return { trained: domains.length, stored, errors };
}

export async function testMLDomainKnowledge(sampleSize = 20): Promise<{ tested: number; passed: number; score: number; gaps: string[] }> {
  const sample = ML_DOMAINS
    .sort(() => Math.random() - 0.5)
    .slice(0, sampleSize);

  let passed = 0;
  const gaps: string[] = [];

  for (const domain of sample) {
    for (const q of domain.trainingQuestions) {
      try {
        const results = await searchMemory(q.q, 5);
        const combined = results.map(r => r.content).join(" ").toLowerCase();
        const matched = q.keywords.filter(kw => combined.includes(kw.toLowerCase()));
        if (matched.length >= Math.ceil(q.keywords.length / 2)) {
          passed++;
        } else {
          gaps.push(`${domain.name}: "${q.q}" — ${matched.length}/${q.keywords.length} keywords`);
        }
      } catch {
        gaps.push(`${domain.name}: error searching for "${q.q}"`);
      }
    }
  }

  const totalQuestions = sample.reduce((s, d) => s + d.trainingQuestions.length, 0);
  const score = totalQuestions > 0 ? Math.round((passed / totalQuestions) * 100) : 0;

  return { tested: totalQuestions, passed, score, gaps };
}
