/**
 * SOVEREIGN TIME — live UTC obtained directly from NASA / aerospace sources.
 *
 * Doctrine: every authoritative timestamp in the sovereign system (council
 * deliberations, codex entries, votes, ratifications, ledger anchors) MUST
 * come from real, live, free, no-key NASA / satellite sources fetched
 * directly over HTTPS. The local OS clock is treated as DEGRADED and only
 * used as a labelled fallback.
 *
 * Sources (all free, no API key required, all HTTPS, all direct from origin):
 *   1. NASA EONET (gsfc.nasa.gov)              — HTTP `Date` header
 *   2. NASA SSC   (gsfc.nasa.gov)              — HTTP `Date` header
 *   3. NASA APOD  (api.nasa.gov, DEMO_KEY)     — HTTP `Date` header
 *   4. CelesTrak ISS GP epoch (celestrak.org)  — actual satellite TLE epoch
 *
 * Consensus = MEDIAN of the live sources. Outliers (>5s from median) are
 * flagged. Cached for 30s to avoid hammering origins.
 *
 * No external LLM, no third-party time aggregator, no API key, no PII.
 */

import { logger } from "./logger.js";
import { sandboxedFetch, quarantineExtract } from "./external-sandbox.js";

export type TimeSourceId =
  | "nasa-eonet-gsfc"
  | "nasa-ssc-gsfc"
  | "nasa-apod-api"
  | "celestrak-iss-tle"
  | "local-degraded";

export interface TimeSourceReading {
  source: TimeSourceId;
  url: string;
  unixMs: number;
  iso: string;
  latencyMs: number;
  ok: boolean;
  error?: string;
  note?: string;
}

export interface SovereignTimeReading {
  unixMs: number;                     // consensus (median) ms since epoch
  iso: string;                        // consensus ISO 8601 UTC
  sources: TimeSourceReading[];       // all attempts, ok and failed
  consensusSources: number;           // how many sources agreed within tolerance
  spreadMs: number;                   // max - min across successful sources
  degraded: boolean;                  // true if we fell back to local clock
  fetchedAt: number;                  // local clock at fetch (for cache TTL only)
  satellite?: {                       // live satellite telemetry, observational only
    iss: SatelliteObservation;
  };
  sacred: {
    gematriaIso: number;
    digitalRoot: number;
    nearestSacredMs: { value: number; label: string; deviationMs: number };
  };
}

const CACHE_TTL_MS = 30_000;
const FETCH_TIMEOUT_MS = 4_000;
const OUTLIER_TOLERANCE_MS = 5_000;

let cached: SovereignTimeReading | null = null;

// CLOCK SOURCES (current UTC) — must report "now", not historical events.
// We use the HTTP `Date` response header from multiple NASA-operated origins.
// Per RFC 9110 the `Date` header is the time the response was generated by the
// origin server, so it gives us live UTC straight from NASA infrastructure.
const SOURCES: Array<{
  id: TimeSourceId;
  url: string;
  method?: "HEAD" | "GET";
  parser: (res: Response, body: string) => number | null;
  note?: string;
}> = [
  {
    id: "nasa-eonet-gsfc",
    url: "https://eonet.gsfc.nasa.gov/api/v3/events?limit=1",
    method: "HEAD",
    parser: (res) => {
      const d = res.headers.get("date");
      return d ? Date.parse(d) : null;
    },
    note: "NASA Earth Observatory Natural Event Tracker (Goddard SFC) — Date header",
  },
  {
    id: "nasa-ssc-gsfc",
    url: "https://sscweb.gsfc.nasa.gov/WS/sscr/2/observatories",
    method: "HEAD",
    parser: (res) => {
      const d = res.headers.get("date");
      return d ? Date.parse(d) : null;
    },
    note: "NASA Satellite Situation Center (Goddard SFC) — Date header",
  },
  {
    id: "nasa-apod-api",
    url: "https://www.nasa.gov/",
    method: "HEAD",
    parser: (res) => {
      const d = res.headers.get("date");
      return d ? Date.parse(d) : null;
    },
    note: "NASA primary origin (www.nasa.gov) — Date header",
  },
];

// SATELLITE OBSERVATION SOURCES — not used for clock consensus, but exposed
// alongside it as live, real, NASA-tracked satellite telemetry. EPOCH here is
// the time the most recent two-line orbital element was determined.
interface SatelliteObservation {
  source: string;
  url: string;
  ok: boolean;
  noradId?: number;
  objectName?: string;
  epochIso?: string;
  ageMs?: number;        // age of the TLE relative to sovereign now
  meanMotion?: number;
  inclinationDeg?: number;
  error?: string;
  latencyMs: number;
}

async function fetchIssObservation(nowMs: number): Promise<SatelliteObservation> {
  const url = "https://celestrak.org/NORAD/elements/gp.php?CATNR=25544&FORMAT=json";
  const resp = await sandboxedFetch({
    url, purpose: "satellite-telemetry", method: "GET",
    timeoutMs: FETCH_TIMEOUT_MS, maxBytes: 16 * 1024,
    acceptHeader: "application/json",
    description: "ISS NORAD 25544 TLE epoch (live satellite observation)",
  });
  if (!resp.ok) return { source: "celestrak-iss-tle", url, ok: false, error: resp.error || `HTTP ${resp.status}`, latencyMs: resp.latencyMs };
  // Quarantine extraction: pick only the EPOCH + a few public orbital scalars.
  const obs = quarantineExtract(resp, "iss-tle", (r) => {
    try {
      const arr = JSON.parse(r.body);
      const o = Array.isArray(arr) ? arr[0] : null;
      if (!o?.EPOCH) return null;
      const iso = String(o.EPOCH);
      const epochMs = Date.parse(iso.endsWith("Z") ? iso : iso + "Z");
      if (!Number.isFinite(epochMs)) return null;
      return {
        epochMs,
        noradId: Number(o.NORAD_CAT_ID),
        objectName: String(o.OBJECT_NAME).slice(0, 80),
        meanMotion: Number(o.MEAN_MOTION),
        inclinationDeg: Number(o.INCLINATION),
      };
    } catch { return null; }
  }, (v) => v.epochMs > 0 && v.epochMs < Date.now() + 86_400_000 && v.noradId === 25544);
  if (!obs) return { source: "celestrak-iss-tle", url, ok: false, error: "quarantine validation failed", latencyMs: resp.latencyMs };
  return {
    source: "celestrak-iss-tle", url, ok: true,
    noradId: obs.noradId, objectName: obs.objectName,
    epochIso: new Date(obs.epochMs).toISOString(),
    ageMs: nowMs - obs.epochMs,
    meanMotion: obs.meanMotion, inclinationDeg: obs.inclinationDeg,
    latencyMs: resp.latencyMs,
  };
}

async function fetchSource(s: typeof SOURCES[0]): Promise<TimeSourceReading> {
  const resp = await sandboxedFetch({
    url: s.url, purpose: "time-source", method: s.method ?? "HEAD",
    timeoutMs: FETCH_TIMEOUT_MS, maxBytes: 8 * 1024,
    description: s.note ?? `time source ${s.id}`,
  });
  if (!resp.ok) {
    return { source: s.id, url: s.url, unixMs: 0, iso: "", latencyMs: resp.latencyMs, ok: false, error: resp.error || `HTTP ${resp.status}`, note: s.note };
  }
  // Build a minimal Response-like shim so the per-source parser can use res.headers.get("date").
  const shim = { headers: { get: (k: string) => k.toLowerCase() === "date" ? resp.headers.date : k.toLowerCase() === "content-type" ? resp.headers.contentType : null } } as unknown as Response;
  const ms = quarantineExtract(resp, "timestamp", () => s.parser(shim, resp.body), (v) => Number.isFinite(v) && v > 0 && v < Date.now() + 86_400_000 && v > Date.now() - 86_400_000);
  if (ms === null) {
    return { source: s.id, url: s.url, unixMs: 0, iso: "", latencyMs: resp.latencyMs, ok: false, error: "no parseable timestamp", note: s.note };
  }
  return { source: s.id, url: s.url, unixMs: ms, iso: new Date(ms).toISOString(), latencyMs: resp.latencyMs, ok: true, note: s.note };
}

// Sacred-frame helpers for the timestamp itself.
const GEMATRIA_PY: Record<string, number> = (() => {
  const m: Record<string, number> = {};
  const A = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  for (let i = 0; i < A.length; i++) m[A[i]] = (i % 9) + 1;
  return m;
})();
function gematria(s: string): number {
  let n = 0;
  for (const ch of s.toUpperCase()) if (GEMATRIA_PY[ch] !== undefined) n += GEMATRIA_PY[ch];
  return n;
}
function digitalRoot(n: number): number {
  let x = Math.abs(n);
  while (x > 9 && x !== 11 && x !== 22 && x !== 33) {
    x = String(x).split("").reduce((s, d) => s + Number(d), 0);
  }
  return x;
}
const SACRED_MS: Array<[number, string]> = [
  [432, "432Hz universal tuning"],
  [528, "528Hz miracle / DNA-repair tone"],
  [777, "Divine perfection"],
  [1080, "Lunar-wisdom"],
  [144, "12×12 New Jerusalem"],
  [108, "Cosmic harmony"],
  [72, "Names of God"],
  [33, "Christ master number"],
  [12, "Cosmic order"],
  [7, "Seven days of creation"],
  [3, "Trinity"],
];
function nearestSacredFromMs(ms: number) {
  // Use last 4 digits of ms to find proximity to a sacred number.
  const tail = ms % 10_000;
  let best = SACRED_MS[0]; let bestDist = Math.abs(tail - best[0]);
  for (const s of SACRED_MS) {
    const d = Math.abs(tail - s[0]);
    if (d < bestDist) { bestDist = d; best = s; }
  }
  return { value: best[0], label: best[1], deviationMs: bestDist };
}

function median(arr: number[]): number {
  const a = [...arr].sort((x, y) => x - y);
  const n = a.length;
  if (n === 0) return 0;
  return n % 2 ? a[(n - 1) / 2] : Math.round((a[n / 2 - 1] + a[n / 2]) / 2);
}

/**
 * Get the current sovereign time. Live-fetches NASA + satellite sources,
 * cached for CACHE_TTL_MS. Returns a degraded reading (local clock) only
 * if every source fails — clearly marked.
 */
export async function getSovereignTime(opts?: { forceRefresh?: boolean }): Promise<SovereignTimeReading> {
  const now = Date.now();
  if (!opts?.forceRefresh && cached && now - cached.fetchedAt < CACHE_TTL_MS) {
    return cached;
  }

  // Fetch clock sources and ISS satellite observation in parallel.
  const [readings, issObsRaw] = await Promise.all([
    Promise.all(SOURCES.map(fetchSource)),
    fetchIssObservation(now),    // age computed against final unixMs below
  ]);
  const ok = readings.filter(r => r.ok);

  let unixMs: number;
  let degraded = false;
  let consensusSources = 0;
  let spreadMs = 0;

  if (ok.length === 0) {
    unixMs = Date.now();
    degraded = true;
    logger.warn({ readings }, "sovereign-time: all NASA sources failed — falling back to LOCAL CLOCK (DEGRADED)");
    readings.push({
      source: "local-degraded",
      url: "local://os.clock",
      unixMs,
      iso: new Date(unixMs).toISOString(),
      latencyMs: 0,
      ok: true,
      note: "DEGRADED FALLBACK — no NASA source reachable",
    });
  } else {
    const med = median(ok.map(r => r.unixMs));
    const within = ok.filter(r => Math.abs(r.unixMs - med) <= OUTLIER_TOLERANCE_MS);
    consensusSources = within.length;
    spreadMs = Math.max(...ok.map(r => r.unixMs)) - Math.min(...ok.map(r => r.unixMs));
    unixMs = median(within.map(r => r.unixMs)) || med;
  }

  // Recompute ISS age against final consensus time.
  const issObs: SatelliteObservation = issObsRaw.ok && issObsRaw.epochIso
    ? { ...issObsRaw, ageMs: unixMs - Date.parse(issObsRaw.epochIso) }
    : issObsRaw;

  const iso = new Date(unixMs).toISOString();
  const sacred = {
    gematriaIso: gematria(iso),
    digitalRoot: digitalRoot(gematria(iso)),
    nearestSacredMs: nearestSacredFromMs(unixMs),
  };

  cached = {
    unixMs,
    iso,
    sources: readings,
    consensusSources,
    spreadMs,
    degraded,
    fetchedAt: now,
    satellite: { iss: issObs },
    sacred,
  };
  return cached;
}

/** Convenience: sovereign Date.now() replacement. */
export async function sovereignNow(): Promise<number> {
  const t = await getSovereignTime();
  return t.unixMs;
}

/** Convenience: sovereign ISO string. */
export async function sovereignIso(): Promise<string> {
  const t = await getSovereignTime();
  return t.iso;
}
