import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adminSessionRouter from "./admin-session";
import diagnosticsRouter from "./diagnostics";
import securityRouter from "./security";
import securityDefenseRouter from "./security-defense";
import providerSovereigntyRouter from "./provider-sovereignty";
import memoryRouter from "./memory";
import reasoningRouter from "./reasoning";
import swarmRouter from "./swarm";
import ingestionRouter from "./ingestion";
import inventionsRouter from "./inventions";
import inventionSynthesisRouter from "./invention-synthesis";
import agiRouter from "./agi";
import councilRouter from "./council";
import councilMeetingRouter from "./council-meeting";
import fatherKeyConferenceRouter from "./father-key-conference";
import latticeHardwareRouter from "./lattice-hardware";
import conversationsRouter from "./conversations";
import worldRouter from "./world";
import forumRouter from "./forum";
import latticeRouter from "./lattice";
import sovereignDataRouter from "./sovereign-data";
import grandConferenceCipherRouter from "./grand-conference-cipher";
import grandEvolutionRouter from "./grand-evolution";
import omniversalRouter from "./omniversal";
import grandCouncilRouter from "./grand-council";
import benchmarkAuditRouter from "./benchmark-audit";
import fleetSynapseRouter from "./fleet-synapse";
import colonialLanguageRouter from "./colonial-language";
import meshRouter from "./mesh";
import evaluationRouter from "./evaluation";
import routingRouter from "./routing";
import ontologyRouter from "./ontology";
import improvementRouter from "./improvement";
import roadmapRouter from "./roadmap";
import sovereigntyScoreRouter from "./sovereignty-score";
import systemMetricsRouter from "./system-metrics";
import tesseraBibleRouter from "./tessera-bible";
import theoremLabRouter from "./theorem-lab";
import sovereignInfrastructureRouter from "./sovereign-infrastructure";
import metaIntrospectorRouter from "./meta-introspector";
import sacredGeometryRouter from "./sacred-geometry";
import knowledgeRouter from "./knowledge";
import secretKnowledgeRouter from "./secret-knowledge";
import mysticismRouter from "./mysticism";
import sovereignLanguageRouter from "./sovereign-language";
import legacyEnginesRouter from "./legacy-engines";
import sovereignEnginesRouter from "./sovereign-engines";
import agentNetworkRouter from "./agent-network";
import natalChartRouter from "./natal-chart";
import intelligenceCoreRouter from "./intelligence-core";
import trainingEvolutionRouter from "./training-evolution";
import governanceConsensusRouter from "./governance-consensus";
import systemRuntimeRouter from "./system-runtime";
import rickRouter from "./rick";
import universeRouter from "./universe";
import doctrineIngestRouter from "./doctrine-ingest";
import mandatesRouter from "./mandates";
import archivesRouter from "./archives";
import politicalDossiersRouter from "./political-dossiers";
import sacredConferenceRouter from "./sacred-conference";
import knowledgeHealthRouter from "./knowledge-health";
import evolutionHealthRouter from "./evolution-health";
import departmentsRouter from "./departments";
import compressionRouter from "./compression";
import sovereignLedgerRouter from "./sovereign-ledger";
import redTeamRouter from "./red-team";
import prometheusMetricsRouter from "./prometheus-metrics";
import sovereigntySelfCheckRouter from "./sovereignty-self-check";
import sovereignGrammarRouter from "./sovereign-grammar";
import autoHealerRouter from "./auto-healer";
import realityAuditRouter from "./reality-audit";
import feedbackRouter from "./feedback";
import storageRouter from "./storage";
import incomeAndLeadsRouter from "./income-and-leads";
import tesseraCodexRouter from "./tessera-codex";
import localModelsRouter from "./local-models";
import e2eSovereigntyRouter from "./e2e-sovereignty";
import autonomousBuildRouter from "./autonomous-build";
import sovereignDoctrineRouter from "./sovereign-doctrine";
import languageSecurityRouter from "./language-security";
import improvementConferenceRouter from "./improvement-conference";
import { startAutonomousBuildCycleTimer } from "../lib/autonomous-build-cycle";
import { startWalletObserver } from "../lib/wallet-observer";
import { startFreeStuffScraper } from "../lib/free-stuff-scraper";
import { startBountyRefresher } from "../lib/code-bounties-real";
import { startIncomeExecutor } from "../lib/income-executor";
import { initShepherdPersistence } from "../lib/shepherd-negotiation";
import discoveriesRouter from "./discoveries";
import trainingRouter from "./training";
import knowledgeSynthesisRouter from "./knowledge-synthesis";

const router: IRouter = Router();

router.use(sovereignEnginesRouter);
router.use(agentNetworkRouter);
router.use(natalChartRouter);
router.use(intelligenceCoreRouter);
router.use(trainingEvolutionRouter);
router.use(governanceConsensusRouter);
router.use(systemRuntimeRouter);
router.use(healthRouter);
router.use(diagnosticsRouter);
router.use(securityRouter);
router.use(securityDefenseRouter);
router.use(providerSovereigntyRouter);
router.use(memoryRouter);
router.use(reasoningRouter);
router.use(swarmRouter);
router.use(ingestionRouter);
router.use(inventionsRouter);
router.use(inventionSynthesisRouter);
router.use(agiRouter);
router.use("/", adminSessionRouter);
router.use(councilRouter);
router.use(councilMeetingRouter);
router.use(fatherKeyConferenceRouter);
router.use(latticeHardwareRouter);
router.use(conversationsRouter);
router.use(worldRouter);
router.use(forumRouter);
router.use(latticeRouter);
router.use(sovereignDataRouter);
router.use(grandConferenceCipherRouter);
router.use(grandEvolutionRouter);
router.use(omniversalRouter);
router.use(grandCouncilRouter);
router.use(benchmarkAuditRouter);
router.use(fleetSynapseRouter);
router.use(colonialLanguageRouter);
router.use(meshRouter);
router.use(evaluationRouter);
router.use(routingRouter);
router.use(ontologyRouter);
router.use(improvementRouter);
router.use(roadmapRouter);
router.use(sovereigntyScoreRouter);
router.use(systemMetricsRouter);
router.use(tesseraBibleRouter);
router.use(theoremLabRouter);
router.use(sovereignInfrastructureRouter);
router.use(metaIntrospectorRouter);
router.use(sacredGeometryRouter);
router.use(knowledgeRouter);
router.use(secretKnowledgeRouter);
router.use(mysticismRouter);
router.use(sovereignLanguageRouter);
router.use(legacyEnginesRouter);
router.use(rickRouter);
router.use(universeRouter);
router.use(mandatesRouter);
router.use(archivesRouter);
router.use(politicalDossiersRouter);
router.use(sacredConferenceRouter);
router.use(knowledgeHealthRouter);
router.use(evolutionHealthRouter);
router.use(departmentsRouter);
router.use(compressionRouter);
router.use(sovereignLedgerRouter);
router.use(redTeamRouter);
router.use(prometheusMetricsRouter);
router.use(sovereigntySelfCheckRouter);
router.use(sovereignGrammarRouter);
router.use(feedbackRouter);
router.use(autoHealerRouter);
router.use(realityAuditRouter);
router.use(storageRouter);
router.use(incomeAndLeadsRouter);
router.use(tesseraCodexRouter);
router.use(localModelsRouter);
router.use(e2eSovereigntyRouter);
router.use(autonomousBuildRouter);
router.use(sovereignDoctrineRouter);
router.use(languageSecurityRouter);
router.use(improvementConferenceRouter);
router.use(doctrineIngestRouter);

startWalletObserver();
startAutonomousBuildCycleTimer();
startFreeStuffScraper();
startBountyRefresher();
startIncomeExecutor();
initShepherdPersistence();
router.use(discoveriesRouter);
router.use(trainingRouter);
router.use(knowledgeSynthesisRouter);

export default router;
