import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import {
  goalsTable, reasoningTracesTable, generatedCodeTable, causalModelsTable,
} from "@workspace/db";
import { desc, eq } from "drizzle-orm";
import { logger } from "../lib/logger";
import vm from "node:vm";
import { validateMeshToken } from "../lib/mesh-auth";
import { meshBroadcast } from "../lib/mesh-bus";

const router: IRouter = Router();

function goalDecomposer(objective: string): { subTasks: any[]; dependencies: Record<string, string[]> } {
  const phases = [
    { id: "research", title: "Research & Analysis", description: `Analyze and gather information about: ${objective.slice(0, 80)}`, priority: 1 },
    { id: "design", title: "Design & Architecture", description: "Design the solution structure and architecture", priority: 2 },
    { id: "implement", title: "Implementation", description: "Build and implement the core components", priority: 3 },
    { id: "test", title: "Testing & Validation", description: "Test and validate the implementation", priority: 4 },
    { id: "deploy", title: "Deployment & Integration", description: "Deploy and integrate into the system", priority: 5 },
    { id: "monitor", title: "Monitoring & Iteration", description: "Monitor results and iterate on improvements", priority: 6 },
  ];
  const deps: Record<string, string[]> = {
    research: [],
    design: ["research"],
    implement: ["design"],
    test: ["implement"],
    deploy: ["test"],
    monitor: ["deploy"],
  };
  return { subTasks: phases, dependencies: deps };
}

function buildReasoningSteps(query: string): any[] {
  return [
    { step: 1, type: "observation", content: `Analyzing query: "${query.slice(0, 100)}"`, timestamp: Date.now() },
    { step: 2, type: "hypothesis", content: "Identifying key variables and relationships", timestamp: Date.now() + 100 },
    { step: 3, type: "analysis", content: "Applying multi-dimensional reasoning framework", timestamp: Date.now() + 200 },
    { step: 4, type: "validation", content: "Cross-checking intermediate conclusions", timestamp: Date.now() + 300 },
    { step: 5, type: "synthesis", content: "Synthesizing final conclusion from all reasoning steps", timestamp: Date.now() + 400 },
  ];
}

function buildCausalGraph(domain: string): { nodes: any[]; edges: any[] } {
  const nodes = [
    { id: "input", label: "Input Condition", type: "cause", description: `Initial state in ${domain}` },
    { id: "mechanism", label: "Causal Mechanism", type: "intermediate", description: "Process linking cause to effect" },
    { id: "moderator", label: "Moderating Factor", type: "moderator", description: "Variable that modifies the causal effect" },
    { id: "output", label: "Effect / Outcome", type: "effect", description: `Observable result in ${domain}` },
    { id: "feedback", label: "Feedback Loop", type: "feedback", description: "Effect that feeds back to the cause" },
  ];
  const edges = [
    { from: "input", to: "mechanism", label: "triggers", strength: 0.85 },
    { from: "mechanism", to: "output", label: "produces", strength: 0.78 },
    { from: "moderator", to: "mechanism", label: "modifies", strength: 0.62 },
    { from: "output", to: "feedback", label: "generates", strength: 0.45 },
    { from: "feedback", to: "input", label: "adjusts", strength: 0.33 },
  ];
  return { nodes, edges };
}

function generateTypeScriptCode(description: string): string {
  const fnName = description
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .trim()
    .split(/\s+/)
    .slice(0, 3)
    .map((w, i) => i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1))
    .join("") || "processData";

  return `/**
 * ${description}
 * Generated by Tessera Reasoning Engine
 * Language: TypeScript
 */

// Type definitions
// interface InputParams { input: string; options?: Record<string, unknown>; }
// interface OutputResult { success: boolean; data: unknown; error?: string; timestamp: number; }

async function ${fnName}(params) {
  const startTime = Date.now();

  try {
    if (!params || !params.input || params.input.trim() === "") {
      throw new Error("Input cannot be empty");
    }

    // Core logic: ${description}
    const processed = params.input.trim().toUpperCase();
    const result = {
      original: params.input,
      processed,
      length: processed.length,
      wordCount: params.input.trim().split(/\\s+/).length,
      options: params.options || {},
    };

    return {
      success: true,
      data: result,
      timestamp: Date.now() - startTime,
    };
  } catch (err) {
    return {
      success: false,
      data: null,
      error: err instanceof Error ? err.message : String(err),
      timestamp: Date.now() - startTime,
    };
  }
}

// Run self-test
${fnName}({ input: "hello world", options: {} }).then(r => {
  console.log("Self-test result:", JSON.stringify(r, null, 2));
}).catch(e => {
  console.error("Self-test error:", e.message);
});
`;
}

function generateTestSuite(code: string, description: string): string {
  const fnMatch = code.match(/export async function (\w+)/);
  const fnName = fnMatch?.[1] ?? "processData";

  return `/**
 * Auto-generated tests for: ${description}
 * Generated by Tessera Reasoning Engine
 */

import { ${fnName} } from "./generated";

describe("${fnName}", () => {
  it("should succeed with valid input", async () => {
    const result = await ${fnName}({ input: "hello world" });
    expect(result.success).toBe(true);
    expect(result.data).toBeDefined();
    expect(result.error).toBeUndefined();
  });

  it("should fail with empty input", async () => {
    const result = await ${fnName}({ input: "" });
    expect(result.success).toBe(false);
    expect(result.error).toBeDefined();
  });

  it("should accept optional options", async () => {
    const result = await ${fnName}({ input: "test", options: { debug: true } });
    expect(result.success).toBe(true);
  });

  it("should return a timestamp", async () => {
    const result = await ${fnName}({ input: "test" });
    expect(typeof result.timestamp).toBe("number");
    expect(result.timestamp).toBeGreaterThanOrEqual(0);
  });

  it("should handle special characters in input", async () => {
    const result = await ${fnName}({ input: "hello! @world #test" });
    expect(result.success).toBe(true);
  });
});
`;
}

async function sandboxExecute(code: string): Promise<{ output: string; error: string | null; exitCode: number }> {
  const logs: string[] = [];
  const sandbox = {
    console: {
      log: (...args: unknown[]) => logs.push(args.map(a => typeof a === "object" ? JSON.stringify(a) : String(a)).join(" ")),
      error: (...args: unknown[]) => logs.push("[ERROR] " + args.map(a => String(a)).join(" ")),
      warn: (...args: unknown[]) => logs.push("[WARN] " + args.map(a => String(a)).join(" ")),
    },
    Math,
    JSON,
    Date,
    parseInt,
    parseFloat,
    Number,
    String,
    Boolean,
    Array,
    Object,
    Promise,
    setTimeout: (_fn: unknown, _ms: unknown) => 0,
    clearTimeout: (_id: unknown) => {},
  };

  try {
    const stripped = code
      .replace(/import\s+.*?from\s+['"][^'"]+['"];?\s*/g, "")
      .replace(/^export\s+(async\s+)?function\s+/gm, "async function ")
      .replace(/export\s+default\s+\w+;?\s*$/m, "")
      .replace(/export\s+\{[^}]+\};?\s*/g, "");

    const script = new vm.Script(stripped);
    const ctx = vm.createContext(sandbox);
    const result = script.runInContext(ctx, { timeout: 3000 });

    if (result && typeof result.then === "function") {
      await result;
    }

    return {
      output: logs.join("\n") || "(no output)",
      error: null,
      exitCode: 0,
    };
  } catch (err) {
    return {
      output: logs.join("\n"),
      error: err instanceof Error ? err.message : "Unknown error",
      exitCode: 1,
    };
  }
}

router.post("/reasoning/goals", async (req, res) => {
  try {
    const { title, objective, priority = 5 } = req.body;
    if (!objective) return res.status(400).json({ error: "objective is required" });

    const { subTasks, dependencies } = goalDecomposer(objective);

    const [goal] = await db.insert(goalsTable).values({
      title: title || objective.slice(0, 60),
      objective,
      priority,
      subTasks,
      dependencies,
      status: "active",
    }).returning();

    logger.info({ module: "reasoning-goals" }, `New goal created: ${goal.id} — ${goal.title}`);

    const rawToken = req.headers["x-admin-token"];
    const token = Array.isArray(rawToken) ? rawToken[0] : rawToken;
    const keyHash = validateMeshToken(token ?? "");
    if (keyHash) {
      meshBroadcast(keyHash, "reasoning:goal-created", {
        id: goal.id,
        title: goal.title,
        objective: goal.objective?.slice(0, 100),
        status: goal.status,
      });
    }

    return res.json(goal);
  } catch (err) {
    logger.error({ module: "reasoning-goals" }, `Failed to create goal: ${err}`);
    return res.status(500).json({ error: "Failed to create goal" });
  }
});

router.get("/reasoning/goals", async (_req, res) => {
  try {
    const goals = await db.select().from(goalsTable).orderBy(desc(goalsTable.createdAt)).limit(50);
    return res.json(goals);
  } catch (err) {
    return res.status(500).json({ error: "Failed to fetch goals" });
  }
});

router.get("/reasoning/goals/:id", async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const [goal] = await db.select().from(goalsTable).where(eq(goalsTable.id, id));
    if (!goal) return res.status(404).json({ error: "Goal not found" });
    return res.json(goal);
  } catch (err) {
    return res.status(500).json({ error: "Failed to fetch goal" });
  }
});

router.patch("/reasoning/goals/:id/status", async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const { status } = req.body;
    const [updated] = await db.update(goalsTable).set({ status, updatedAt: new Date() }).where(eq(goalsTable.id, id)).returning();
    return res.json(updated);
  } catch (err) {
    return res.status(500).json({ error: "Failed to update goal" });
  }
});

router.post("/reasoning/traces", async (req, res) => {
  try {
    const { query, goalId, model = "claude-sonnet-4-20250514" } = req.body;
    if (!query) return res.status(400).json({ error: "query is required" });

    const steps = buildReasoningSteps(query);

    const conclusion = `Based on multi-step reasoning analysis of "${query.slice(0, 60)}...": ` +
      `The evidence suggests a structured approach focusing on decomposing the problem into verifiable components, ` +
      `validating each intermediate conclusion, and synthesizing a robust final answer through causal inference.`;

    const [trace] = await db.insert(reasoningTracesTable).values({
      goalId: goalId || null,
      title: `Reasoning: ${query.slice(0, 50)}`,
      query,
      steps,
      conclusion,
      model,
      status: "complete",
      completedAt: new Date(),
    }).returning();

    const rawToken = req.headers["x-admin-token"];
    const token = Array.isArray(rawToken) ? rawToken[0] : rawToken;
    const keyHash = validateMeshToken(token ?? "");
    if (keyHash) {
      meshBroadcast(keyHash, "reasoning:trace-completed", {
        id: trace.id,
        title: trace.title,
        queryPreview: query.slice(0, 80),
        model,
        stepCount: steps.length,
      });
    }

    return res.json(trace);
  } catch (err) {
    logger.error({ module: "reasoning-traces" }, `Failed to create trace: ${err}`);
    return res.status(500).json({ error: "Failed to create trace" });
  }
});

router.get("/reasoning/traces", async (_req, res) => {
  try {
    const traces = await db.select().from(reasoningTracesTable).orderBy(desc(reasoningTracesTable.createdAt)).limit(50);
    return res.json(traces);
  } catch (err) {
    return res.status(500).json({ error: "Failed to fetch traces" });
  }
});

router.get("/reasoning/traces/:id", async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const [trace] = await db.select().from(reasoningTracesTable).where(eq(reasoningTracesTable.id, id));
    if (!trace) return res.status(404).json({ error: "Trace not found" });
    return res.json(trace);
  } catch (err) {
    return res.status(500).json({ error: "Failed to fetch trace" });
  }
});

router.post("/reasoning/causal", async (req, res) => {
  try {
    const { title, domain, counterfactual } = req.body;
    if (!domain) return res.status(400).json({ error: "domain is required" });

    const { nodes, edges } = buildCausalGraph(domain);

    const counterfactuals = counterfactual
      ? [{ query: counterfactual, analysis: `If ${counterfactual}: The causal chain in ${domain} would be disrupted at the mechanism level, leading to an estimated 40-65% change in the expected outcome. Key moderating factors would amplify this effect under high-stress conditions.`, confidence: 0.72, timestamp: Date.now() }]
      : [];

    const [model] = await db.insert(causalModelsTable).values({
      title: title || `Causal Model: ${domain}`,
      domain,
      nodes,
      edges,
      counterfactuals,
    }).returning();

    return res.json(model);
  } catch (err) {
    logger.error({ module: "reasoning-causal" }, `Failed to create causal model: ${err}`);
    return res.status(500).json({ error: "Failed to create causal model" });
  }
});

router.get("/reasoning/causal", async (_req, res) => {
  try {
    const models = await db.select().from(causalModelsTable).orderBy(desc(causalModelsTable.createdAt)).limit(30);
    return res.json(models);
  } catch (err) {
    return res.status(500).json({ error: "Failed to fetch causal models" });
  }
});

router.post("/reasoning/counterfactual", async (req, res) => {
  try {
    const { modelId, query } = req.body;
    if (!modelId || !query) return res.status(400).json({ error: "modelId and query are required" });

    const [model] = await db.select().from(causalModelsTable).where(eq(causalModelsTable.id, modelId));
    if (!model) return res.status(404).json({ error: "Causal model not found" });

    const nodes = model.nodes as any[];
    const edges = model.edges as any[];
    const avgEdgeStrength = edges.length > 0
      ? edges.reduce((s: number, e: any) => s + (e.strength ?? 0.5), 0) / edges.length
      : 0.5;
    const graphDensity = nodes.length > 0 ? Math.min(1, edges.length / (nodes.length * 2)) : 0;
    const queryComplexity = Math.min(1, query.split(/\s+/).length / 30);

    const { getAllProviderProfiles } = await import("../lib/provider-registry");
    const profiles = await getAllProviderProfiles();
    const avgProviderReliability = profiles.length > 0
      ? profiles.reduce((s: number, p: any) => s + (p.reliabilityScore ?? 50), 0) / profiles.length / 100
      : 0.5;

    const computedConfidence = Math.round(
      (avgEdgeStrength * 0.4 + graphDensity * 0.25 + (1 - queryComplexity) * 0.15 + avgProviderReliability * 0.2) * 100
    ) / 100;

    const newCounterfactual = {
      query,
      analysis: `Counterfactual analysis for "${query.slice(0, 80)}": ` +
        `Intervening at this point in the ${model.domain} causal chain would propagate through ${nodes.length} nodes. ` +
        `The primary effect pathway would be altered, with cascading consequences across ${edges.length} causal edges. ` +
        `Confidence derived from: causal edge strength (${avgEdgeStrength.toFixed(2)}), graph density (${graphDensity.toFixed(2)}), query complexity, and provider reliability (${(avgProviderReliability * 100).toFixed(0)}%).`,
      confidence: Math.max(0.45, Math.min(0.95, computedConfidence)),
      confidenceFactors: {
        avgEdgeStrength: Math.round(avgEdgeStrength * 100) / 100,
        graphDensity: Math.round(graphDensity * 100) / 100,
        queryComplexity: Math.round(queryComplexity * 100) / 100,
        avgProviderReliability: Math.round(avgProviderReliability * 100) / 100,
        profilesUsed: profiles.length,
      },
      timestamp: Date.now(),
    };

    const updatedCounterfactuals = [...(model.counterfactuals as any[]), newCounterfactual];

    const [updated] = await db.update(causalModelsTable)
      .set({ counterfactuals: updatedCounterfactuals })
      .where(eq(causalModelsTable.id, modelId))
      .returning();

    return res.json({ counterfactual: newCounterfactual, model: updated });
  } catch (err) {
    return res.status(500).json({ error: "Failed to run counterfactual" });
  }
});

router.post("/reasoning/codegen", async (req, res) => {
  try {
    const { description, goalId, language = "typescript" } = req.body;
    if (!description) return res.status(400).json({ error: "description is required" });

    const code = generateTypeScriptCode(description);
    const tests = generateTestSuite(code, description);

    const [generated] = await db.insert(generatedCodeTable).values({
      goalId: goalId || null,
      description,
      language,
      code,
      tests,
      status: "generated",
    }).returning();

    return res.json(generated);
  } catch (err) {
    logger.error({ module: "reasoning-codegen" }, `Failed to generate code: ${err}`);
    return res.status(500).json({ error: "Failed to generate code" });
  }
});

router.get("/reasoning/codegen", async (_req, res) => {
  try {
    const generated = await db.select().from(generatedCodeTable).orderBy(desc(generatedCodeTable.createdAt)).limit(50);
    return res.json(generated);
  } catch (err) {
    return res.status(500).json({ error: "Failed to fetch generated code" });
  }
});

router.post("/reasoning/execute", async (req, res) => {
  try {
    const { codeId, code } = req.body;

    const targetCode = code || (codeId && (await db.select().from(generatedCodeTable).where(eq(generatedCodeTable.id, codeId)).then(r => r[0]?.code)));
    if (!targetCode) return res.status(400).json({ error: "code or codeId is required" });

    const result = await sandboxExecute(targetCode);

    if (codeId) {
      await db.update(generatedCodeTable)
        .set({
          executionResult: result,
          status: result.exitCode === 0 ? "executed" : "failed",
        })
        .where(eq(generatedCodeTable.id, codeId));
    }

    return res.json(result);
  } catch (err) {
    logger.error({ module: "reasoning-execute" }, `Execution failed: ${err}`);
    return res.status(500).json({ error: "Execution failed", details: String(err) });
  }
});

router.get("/reasoning/dashboard", async (_req, res) => {
  try {
    const [
      goals,
      traces,
      codeItems,
      causalModels,
    ] = await Promise.all([
      db.select().from(goalsTable).orderBy(desc(goalsTable.createdAt)).limit(10),
      db.select().from(reasoningTracesTable).orderBy(desc(reasoningTracesTable.createdAt)).limit(10),
      db.select().from(generatedCodeTable).orderBy(desc(generatedCodeTable.createdAt)).limit(10),
      db.select().from(causalModelsTable).orderBy(desc(causalModelsTable.createdAt)).limit(10),
    ]);

    const goalStats = {
      total: goals.length,
      active: goals.filter(g => g.status === "active").length,
      complete: goals.filter(g => g.status === "complete").length,
      pending: goals.filter(g => g.status === "pending").length,
    };

    const codeStats = {
      total: codeItems.length,
      executed: codeItems.filter(c => c.status === "executed").length,
      generated: codeItems.filter(c => c.status === "generated").length,
      failed: codeItems.filter(c => c.status === "failed").length,
    };

    return res.json({
      goals: goals.slice(0, 5),
      traces: traces.slice(0, 5),
      code: codeItems.slice(0, 5),
      causalModels: causalModels.slice(0, 5),
      stats: {
        goals: goalStats,
        traces: { total: traces.length, complete: traces.filter(t => t.status === "complete").length },
        code: codeStats,
        causalModels: { total: causalModels.length },
      },
    });
  } catch (err) {
    logger.error({ module: "reasoning-dashboard" }, `Failed to fetch dashboard data: ${err}`);
    return res.status(500).json({ error: "Failed to fetch dashboard data" });
  }
});

export default router;
