/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalResearchUseRouteImport } from './routes/legal.research-use'
import { Route as LegalReturnsRouteImport } from './routes/legal.returns'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalResearchUseRoute = LegalResearchUseRouteImport.update({
  id: '/legal/research-use',
  path: '/legal/research-use',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReturnsRoute = LegalReturnsRouteImport.update({
  id: '/legal/returns',
  path: '/legal/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/testing': typeof TestingRoute
  '/wholesale': typeof WholesaleRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/research-use': typeof LegalResearchUseRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/testing': typeof TestingRoute
  '/wholesale': typeof WholesaleRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/research-use': typeof LegalResearchUseRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/testing': typeof TestingRoute
  '/wholesale': typeof WholesaleRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/research-use': typeof LegalResearchUseRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/affiliates'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/subscriptions'
    | '/testing'
    | '/wholesale'
    | '/legal/privacy'
    | '/legal/research-use'
    | '/legal/returns'
    | '/legal/terms'
    | '/product/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/affiliates'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/subscriptions'
    | '/testing'
    | '/wholesale'
    | '/legal/privacy'
    | '/legal/research-use'
    | '/legal/returns'
    | '/legal/terms'
    | '/product/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/affiliates'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/subscriptions'
    | '/testing'
    | '/wholesale'
    | '/legal/privacy'
    | '/legal/research-use'
    | '/legal/returns'
    | '/legal/terms'
    | '/product/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AffiliatesRoute: typeof AffiliatesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TestingRoute: typeof TestingRoute
  WholesaleRoute: typeof WholesaleRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalResearchUseRoute: typeof LegalResearchUseRoute
  LegalReturnsRoute: typeof LegalReturnsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/research-use': {
      id: '/legal/research-use'
      path: '/legal/research-use'
      fullPath: '/legal/research-use'
      preLoaderRoute: typeof LegalResearchUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/returns': {
      id: '/legal/returns'
      path: '/legal/returns'
      fullPath: '/legal/returns'
      preLoaderRoute: typeof LegalReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AffiliatesRoute: AffiliatesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TestingRoute: TestingRoute,
  WholesaleRoute: WholesaleRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalResearchUseRoute: LegalResearchUseRoute,
  LegalReturnsRoute: LegalReturnsRoute,
  LegalTermsRoute: LegalTermsRoute,
  ProductIdRoute: ProductIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
