// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sovereign/CouncilVoteCard.tsx": () => import("../components/mockups/sovereign/CouncilVoteCard.tsx"),
  "./components/mockups/sovereign/FrequencyMeter.tsx": () => import("../components/mockups/sovereign/FrequencyMeter.tsx"),
  "./components/mockups/sovereign/RedTeamTicker.tsx": () => import("../components/mockups/sovereign/RedTeamTicker.tsx"),
  "./components/mockups/sovereign/SovereigntyBadge.tsx": () => import("../components/mockups/sovereign/SovereigntyBadge.tsx")
};
