import { useState, useEffect } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Code2, Copy, Check, Play, Users, GitBranch, Loader2, Terminal, Cpu, Zap, RefreshCw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

export default function AgentCodeBuildingPage({ embedded }: { embedded?: boolean } = {}) {
  useEffect(() => { document.title = "Agent Code Building | Tessera"; }, []);
  const { toast } = useToast();
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);

  const { data, isLoading } = useQuery<any>({ queryKey: ["/api/agent-code-building"], refetchInterval: 15000 });

  const { data: autoData } = useQuery<any>({ queryKey: ["/api/agent-code-building/auto"], refetchInterval: 10000 });

  const generateMutation = useMutation({
    mutationFn: async () => {
      const modules = ["sovereign-kernel", "tesseralang-compiler", "consciousness-engine", "interdimensional-bridge", "coin-launcher", "parallel-universe-protocol", "quantum-networking", "autonomous-income"];
      const mod = modules[Math.floor(Math.random() * modules.length)];
      const res = await apiRequest("POST", "/api/agent-code-building/generate", {
        module: mod,
        description: `Build the ${mod.replace(/-/g, " ")} module with full implementation`,
      });
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/agent-code-building"] });
      queryClient.invalidateQueries({ queryKey: ["/api/agent-code-building/auto"] });
      toast({ title: "Code Generated", description: "Agents have collaboratively built new code" });
    },
  });

  const copyCode = (code: string, idx: number) => {
    navigator.clipboard.writeText(code);
    setCopiedIdx(idx);
    toast({ title: "Copied!", description: "Code copied to clipboard" });
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  const allAutoCode = autoData?.autoGenerated || [];

  return (
    <div className={`${embedded ? "" : "min-h-screen"} bg-background text-white flex flex-col`} data-testid="agent-code-building-page">
      <div className="border-b border-white/8 bg-gradient-to-r from-emerald-950/30 via-[#060610] to-cyan-950/30 px-3 py-3">
        <div className="flex items-center gap-2 mb-2">
          <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-emerald-500 to-cyan-500 flex items-center justify-center shadow-lg shadow-emerald-500/20 shrink-0">
            <Code2 className="w-4 h-4 text-white" />
          </div>
          <div className="flex-1 min-w-0">
            <h1 className="text-base font-bold bg-gradient-to-r from-emerald-300 via-cyan-300 to-blue-300 bg-clip-text text-transparent" data-testid="text-code-building-title">
              AUTONOMOUS CODE BUILDING
            </h1>
            <p className="text-[9px] text-slate-500 truncate">26 agents building code live across all modules</p>
          </div>
          <Badge className="bg-emerald-500/15 text-emerald-400 border-emerald-500/30 text-[9px] shrink-0" data-testid="badge-agents-active">
            {data?.agents?.filter((a: any) => a.status === "coding").length || 0} LIVE
          </Badge>
        </div>

        <div className="flex items-center gap-2 text-[9px]">
          <div className="flex items-center gap-1 text-emerald-400">
            <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
            <span className="font-mono">Auto-building every 90s</span>
          </div>
          <span className="text-white/20">|</span>
          <span className="text-cyan-400 font-mono">{allAutoCode.length} blocks generated</span>
        </div>
      </div>

      <div className="flex-1 overflow-auto pb-20 p-3 space-y-3">
        {isLoading && (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="w-6 h-6 animate-spin text-emerald-400/50" />
          </div>
        )}

        {data && (
          <>
            <div className="bg-gradient-to-br from-emerald-950/40 to-cyan-950/30 rounded-xl border border-emerald-500/20 p-3">
              <div className="flex items-center gap-2 mb-2">
                <Cpu className="w-3.5 h-3.5 text-emerald-400" />
                <h2 className="text-xs font-bold text-emerald-300">{data.currentBuild?.version}</h2>
                <Badge className="bg-cyan-500/15 text-cyan-400 border-cyan-500/30 text-[8px] ml-auto">
                  {data.currentBuild?.progress}%
                </Badge>
              </div>
              <div className="flex flex-wrap gap-1 mb-2">
                {data.currentBuild?.modules?.map((mod: string) => (
                  <div key={mod} className="bg-black/30 rounded-md px-2 py-1 border border-emerald-500/10">
                    <p className="text-[8px] font-bold text-emerald-400 uppercase">{mod}</p>
                  </div>
                ))}
              </div>
              <div className="w-full bg-black/40 rounded-full h-1.5">
                <div className="bg-gradient-to-r from-emerald-500 to-cyan-500 h-1.5 rounded-full transition-all" style={{ width: `${data.currentBuild?.progress || 0}%` }} />
              </div>
            </div>

            <div className="bg-black/30 rounded-xl border border-white/8 p-3">
              <div className="flex items-center gap-2 mb-2">
                <Users className="w-3.5 h-3.5 text-cyan-400" />
                <h3 className="text-xs font-bold text-cyan-300">AGENTS ({data.agents?.length || 0})</h3>
              </div>
              <div className="grid grid-cols-4 gap-1">
                {data.agents?.slice(0, 26).map((agent: any) => (
                  <div key={agent.id} className={cn(
                    "rounded-md p-1 border text-center",
                    agent.status === "coding" ? "border-emerald-500/20 bg-emerald-500/5" : "border-amber-500/20 bg-amber-500/5"
                  )} data-testid={`agent-status-${agent.id}`}>
                    <p className="text-[8px] font-bold text-white truncate">{agent.name}</p>
                    <p className={cn("text-[7px] font-bold", agent.status === "coding" ? "text-emerald-400" : "text-amber-400")}>
                      {agent.status === "coding" ? "CODING" : "REVIEW"}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            <button
              onClick={() => generateMutation.mutate()}
              disabled={generateMutation.isPending}
              className="w-full bg-gradient-to-r from-emerald-600 to-cyan-600 hover:from-emerald-500 hover:to-cyan-500 text-white font-bold py-2.5 rounded-xl flex items-center justify-center gap-2 transition-all active:scale-95 min-h-[44px] text-sm"
              data-testid="button-generate-code"
            >
              {generateMutation.isPending ? (
                <><Loader2 className="w-4 h-4 animate-spin" /> Agents Building...</>
              ) : (
                <><Zap className="w-4 h-4" /> Generate Now (All Modules)</>
              )}
            </button>

            {allAutoCode.length > 0 && (
              <div className="bg-black/30 rounded-xl border border-emerald-500/20 p-3">
                <div className="flex items-center gap-2 mb-2">
                  <Zap className="w-3.5 h-3.5 text-emerald-400" />
                  <h3 className="text-xs font-bold text-emerald-300">LIVE AUTO-GENERATED CODE</h3>
                  <span className="text-[8px] text-emerald-400/60 ml-auto font-mono">{allAutoCode.length} blocks</span>
                </div>
                <div className="space-y-2">
                  {allAutoCode.slice(0, 8).map((contrib: any, idx: number) => (
                    <div key={idx} className="bg-black/40 rounded-lg border border-white/5 overflow-hidden">
                      <div className="flex items-center justify-between px-2 py-1.5 border-b border-white/5 bg-white/[0.02]">
                        <div className="flex items-center gap-1.5 min-w-0">
                          <div className="w-4 h-4 rounded bg-emerald-500/20 flex items-center justify-center shrink-0">
                            <Code2 className="w-2.5 h-2.5 text-emerald-400" />
                          </div>
                          <p className="text-[10px] font-bold text-emerald-300 truncate">{contrib.agentName}</p>
                          <span className="text-[8px] text-cyan-400/60 font-mono shrink-0">{contrib.module}</span>
                        </div>
                        <button
                          onClick={() => copyCode(contrib.code, idx)}
                          className="flex items-center gap-1 text-[9px] text-slate-400 hover:text-white transition-colors px-1.5 py-0.5 rounded hover:bg-white/5 shrink-0"
                          data-testid={`button-copy-auto-${idx}`}
                        >
                          {copiedIdx === idx ? <Check className="w-2.5 h-2.5 text-emerald-400" /> : <Copy className="w-2.5 h-2.5" />}
                          {copiedIdx === idx ? "Copied" : "Copy"}
                        </button>
                      </div>
                      <pre className="p-2 text-[10px] text-emerald-200/80 overflow-x-auto font-mono whitespace-pre-wrap max-h-[200px] overflow-y-auto break-all" style={{ wordBreak: "break-word" }} data-testid={`auto-code-block-${idx}`}>
                        {contrib.code}
                      </pre>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {generateMutation.data && (
              <div className="bg-black/30 rounded-xl border border-violet-500/20 p-3">
                <div className="flex items-center gap-2 mb-2">
                  <GitBranch className="w-3.5 h-3.5 text-violet-400" />
                  <h3 className="text-xs font-bold text-violet-300">GENERATED — {generateMutation.data.module}</h3>
                </div>
                {generateMutation.data.contributions?.map((contrib: any, idx: number) => (
                  <div key={idx} className="mb-2 bg-black/40 rounded-lg border border-white/5 overflow-hidden">
                    <div className="flex items-center justify-between px-2 py-1.5 border-b border-white/5 bg-white/[0.02]">
                      <div className="flex items-center gap-1.5">
                        <Code2 className="w-3 h-3 text-emerald-400" />
                        <p className="text-[10px] font-bold text-emerald-300">{contrib.agentName}</p>
                      </div>
                      <button
                        onClick={() => copyCode(contrib.code, 200 + idx)}
                        className="flex items-center gap-1 text-[9px] text-slate-400 hover:text-white px-1.5 py-0.5 rounded hover:bg-white/5"
                        data-testid={`button-copy-code-${idx}`}
                      >
                        {copiedIdx === 200 + idx ? <Check className="w-2.5 h-2.5 text-emerald-400" /> : <Copy className="w-2.5 h-2.5" />}
                        {copiedIdx === 200 + idx ? "Copied" : "Copy"}
                      </button>
                    </div>
                    <pre className="p-2 text-[10px] text-emerald-200/80 overflow-x-auto font-mono whitespace-pre-wrap max-h-[200px] overflow-y-auto break-all" style={{ wordBreak: "break-word" }} data-testid={`code-block-${idx}`}>
                      {contrib.code}
                    </pre>
                  </div>
                ))}
              </div>
            )}

            {data.codeProposals?.length > 0 && (
              <div className="bg-black/30 rounded-xl border border-white/8 p-3">
                <h3 className="text-xs font-bold text-amber-300 mb-2">RECENT CODE PROPOSALS</h3>
                {data.codeProposals.map((proposal: any, idx: number) => (
                  <div key={idx} className="mb-2 bg-black/20 rounded-lg border border-white/5 p-2">
                    <p className="text-[10px] font-bold text-white mb-0.5 break-words">{proposal.topicTitle}</p>
                    <p className="text-[9px] text-slate-500 mb-1.5">
                      {proposal.contributors?.join(", ")} | {proposal.codeSnippets?.length || 0} blocks
                    </p>
                    {proposal.codeSnippets?.slice(0, 1).map((snippet: any, si: number) => (
                      <div key={si} className="bg-black/30 rounded-md p-1.5 border border-white/5">
                        <div className="flex items-center justify-between mb-0.5">
                          <p className="text-[9px] font-bold text-cyan-400">{snippet.author}</p>
                          <button
                            onClick={() => copyCode(snippet.content, 300 + idx * 10 + si)}
                            className="text-[8px] text-slate-500 hover:text-white"
                            data-testid={`button-copy-snippet-${idx}-${si}`}
                          >
                            {copiedIdx === 300 + idx * 10 + si ? "Copied" : "Copy"}
                          </button>
                        </div>
                        <pre className="text-[9px] text-emerald-200/60 font-mono whitespace-pre-wrap max-h-[100px] overflow-y-auto break-all" style={{ wordBreak: "break-word" }}>
                          {snippet.content.slice(0, 400)}
                        </pre>
                      </div>
                    ))}
                  </div>
                ))}
              </div>
            )}

            <div className="bg-black/30 rounded-xl border border-white/8 p-2.5">
              <p className="text-[9px] text-slate-500 text-center">
                Total lines: {data.totalLinesGenerated?.toLocaleString() || "0"} | Projects: {data.activeProjects || 0} | Auto-blocks: {allAutoCode.length}
              </p>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
