import React from "react";
import { useState, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Vote, CheckCircle, XCircle, Clock, Users, ChevronDown, ChevronRight, Plus, Send, Zap, Bot, MessageSquare, RefreshCw, Activity } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { apiRequest } from "@/lib/queryClient";

interface ConsensusVote {
  agentId: string;
  agentName: string;
  vote: "approve" | "reject" | "abstain";
  reasoning: string;
  timestamp: number;
  confidence: number;
}

interface ConsensusProposal {
  id: string;
  title: string;
  description: string;
  proposedBy: string;
  category: string;
  votes: ConsensusVote[];
  status: "voting" | "approved" | "rejected" | "implemented";
  requiredMajority: number;
  createdAt: number;
  resolvedAt?: number;
  implementationNotes?: string;
  source?: "conference" | "chat" | "self-proposal" | "manual";
  sourceId?: string | number;
  executionStatus?: "pending" | "queued" | "executed" | "failed";
  actionRegistryId?: string;
  autoGenerated?: boolean;
}

interface PipelineStatus {
  totalConferenceProposalLinks: number;
  totalChatConversationsWithProposals: number;
  totalProposalsGenerated: number;
  recentActivity: Array<{ source: string; proposalCount: number; triggeredAt: number }>;
}

const STATUS_COLORS: Record<string, string> = {
  approved: "bg-green-500/20 text-green-400 border-green-500/30",
  rejected: "bg-red-500/20 text-red-400 border-red-500/30",
  voting: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  implemented: "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
};

const CATEGORY_COLORS: Record<string, string> = {
  feature: "text-blue-400", security: "text-red-400", infrastructure: "text-orange-400",
  governance: "text-purple-400", income: "text-green-400", community: "text-pink-400",
};

const SOURCE_LABELS: Record<string, { label: string; icon: React.JSX.Element; color: string }> = {
  conference: { label: "Conference", icon: <Users className="w-3 h-3" />, color: "text-blue-400 bg-blue-500/10 border-blue-500/20" },
  chat: { label: "Chat", icon: <MessageSquare className="w-3 h-3" />, color: "text-cyan-400 bg-cyan-500/10 border-cyan-500/20" },
  "self-proposal": { label: "Self-Proposal", icon: <Bot className="w-3 h-3" />, color: "text-violet-400 bg-violet-500/10 border-violet-500/20" },
  manual: { label: "Manual", icon: <Plus className="w-3 h-3" />, color: "text-slate-400 bg-slate-500/10 border-slate-500/20" },
};

const EXEC_STATUS_COLORS: Record<string, string> = {
  queued: "text-yellow-400",
  executed: "text-green-400",
  failed: "text-red-400",
  pending: "text-slate-400",
};

export default function ConsensusPage({ embedded }: { embedded?: boolean }) {
  useEffect(() => { document.title = "Consensus & Governance | Tessera"; }, []);
  const [expandedProposal, setExpandedProposal] = useState<string | null>(null);
  const [showNewForm, setShowNewForm] = useState(false);
  const [newTitle, setNewTitle] = useState("");
  const [newDesc, setNewDesc] = useState("");
  const [newCategory, setNewCategory] = useState("feature");
  const [filterSource, setFilterSource] = useState<string>("all");
  const [showPipelineFeed, setShowPipelineFeed] = useState(true);
  const queryClient = useQueryClient();

  const { data } = useQuery<{
    proposals: ConsensusProposal[];
    stats: { total: number; approved: number; rejected: number; voting: number; avgApprovalRate: number };
  }>({ queryKey: ["/api/consensus/proposals"], refetchInterval: 5000 });

  const { data: pipelineData } = useQuery<PipelineStatus>({
    queryKey: ["/api/proposal-pipeline/status"],
    refetchInterval: 15000,
  });

  const { data: selfProposalData } = useQuery<{ totalCycles: number; running: boolean; lastCycle?: { totalPassed: number; totalProposals: number; completedAt?: number } }>({
    queryKey: ["/api/self-proposal/status"],
    refetchInterval: 30000,
  });

  const createProposal = useMutation({
    mutationFn: async (payload: { title: string; description: string; category: string }) => {
      const res = await apiRequest("POST", "/api/consensus/propose", payload);
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/consensus/proposals"] });
      setShowNewForm(false);
      setNewTitle("");
      setNewDesc("");
    },
  });

  const triggerSelfProposal = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/self-proposal/trigger", {});
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/self-proposal/status"] });
    },
  });

  const allProposals = data?.proposals || [];
  const stats = data?.stats;

  const filteredProposals = filterSource === "all"
    ? allProposals
    : filterSource === "auto"
    ? allProposals.filter(p => p.autoGenerated || (p.source && p.source !== "manual"))
    : allProposals.filter(p => p.source === filterSource);

  const autoGeneratedCount = allProposals.filter(p => p.autoGenerated || (p.source && p.source !== "manual")).length;

  return (
    <div className={`${embedded ? "" : "min-h-screen"} bg-black text-white p-4 md:p-6`} data-testid="consensus-page">
      <div className="max-w-6xl mx-auto space-y-6">
        <div className="flex items-center gap-3">
          <Vote className="w-8 h-8 text-purple-400" />
          <div>
            <h1 className="text-2xl font-bold" data-testid="text-consensus-title">2/3 Consensus Governance</h1>
            <p className="text-sm text-slate-400">All major decisions require 2/3 supermajority from the 27-agent swarm</p>
          </div>
          <div className="ml-auto flex items-center gap-2">
            <button
              className="bg-violet-500/20 text-violet-400 border border-violet-500/30 rounded-lg px-3 py-1.5 text-sm flex items-center gap-1.5 hover:bg-violet-500/30 transition disabled:opacity-50"
              onClick={() => triggerSelfProposal.mutate()}
              disabled={triggerSelfProposal.isPending || selfProposalData?.running}
              title="Trigger a 24-hour self-proposal cycle"
            >
              <Bot className="w-4 h-4" />
              Self-Propose
            </button>
            <button
              className="bg-purple-500/20 text-purple-400 border border-purple-500/30 rounded-lg px-3 py-1.5 text-sm flex items-center gap-1.5 hover:bg-purple-500/30 transition"
              onClick={() => setShowNewForm(!showNewForm)}
              data-testid="button-new-proposal"
            >
              <Plus className="w-4 h-4" />
              New Proposal
            </button>
          </div>
        </div>

        {stats && (
          <div className="grid grid-cols-2 md:grid-cols-6 gap-3">
            <div className="bg-slate-900/50 border border-slate-700 rounded-lg p-3 text-center">
              <div className="text-2xl font-bold text-slate-200">{stats.total}</div>
              <div className="text-xs text-slate-400">Total Proposals</div>
            </div>
            <div className="bg-slate-900/50 border border-green-500/30 rounded-lg p-3 text-center">
              <div className="text-2xl font-bold text-green-400" data-testid="text-approved-count">{stats.approved}</div>
              <div className="text-xs text-slate-400">Approved</div>
            </div>
            <div className="bg-slate-900/50 border border-red-500/30 rounded-lg p-3 text-center">
              <div className="text-2xl font-bold text-red-400" data-testid="text-rejected-count">{stats.rejected}</div>
              <div className="text-xs text-slate-400">Rejected</div>
            </div>
            <div className="bg-slate-900/50 border border-yellow-500/30 rounded-lg p-3 text-center">
              <div className="text-2xl font-bold text-yellow-400">{stats.voting}</div>
              <div className="text-xs text-slate-400">In Voting</div>
            </div>
            <div className="bg-slate-900/50 border border-purple-500/30 rounded-lg p-3 text-center">
              <div className="text-2xl font-bold text-purple-400">{stats.avgApprovalRate}%</div>
              <div className="text-xs text-slate-400">Avg Approval</div>
            </div>
            <div className="bg-slate-900/50 border border-violet-500/30 rounded-lg p-3 text-center">
              <div className="text-2xl font-bold text-violet-400">{autoGeneratedCount}</div>
              <div className="text-xs text-slate-400">Auto-Generated</div>
            </div>
          </div>
        )}

        {showPipelineFeed && (
          <div className="bg-slate-900/50 border border-violet-500/20 rounded-lg p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Activity className="w-4 h-4 text-violet-400" />
                <h3 className="text-sm font-medium text-violet-300">Autonomous Pipeline Activity</h3>
                <div className="w-2 h-2 bg-violet-400 rounded-full animate-pulse" />
              </div>
              <button
                className="text-xs text-slate-500 hover:text-slate-300 transition"
                onClick={() => setShowPipelineFeed(false)}
              >
                hide
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
              <div className="bg-black/30 rounded p-2.5 border border-slate-700">
                <div className="text-slate-400 mb-1">Conference Extractions</div>
                <div className="text-xl font-bold text-blue-400">{pipelineData?.totalConferenceProposalLinks || 0}</div>
                <div className="text-slate-500">conferences → proposals</div>
              </div>
              <div className="bg-black/30 rounded p-2.5 border border-slate-700">
                <div className="text-slate-400 mb-1">Chat Conversations</div>
                <div className="text-xl font-bold text-cyan-400">{pipelineData?.totalChatConversationsWithProposals || 0}</div>
                <div className="text-slate-500">triggered proposals</div>
              </div>
              <div className="bg-black/30 rounded p-2.5 border border-slate-700">
                <div className="text-slate-400 mb-1">Self-Proposal Engine</div>
                <div className="text-xl font-bold text-violet-400">
                  {selfProposalData?.running ? <span className="text-yellow-400 text-sm animate-pulse">Running...</span> : (selfProposalData?.totalCycles || 0)}
                </div>
                <div className="text-slate-500">{selfProposalData?.running ? "cycle active" : "cycles completed"}</div>
              </div>
            </div>

            {pipelineData?.recentActivity && pipelineData.recentActivity.length > 0 && (
              <div className="space-y-1">
                <div className="text-xs text-slate-500 font-medium">Recent Activity:</div>
                {pipelineData.recentActivity.slice(0, 5).map((a, i) => (
                  <div key={i} className="flex items-center gap-2 text-xs text-slate-400">
                    <Zap className="w-3 h-3 text-violet-400 shrink-0" />
                    <span>{a.source}</span>
                    <span className="text-violet-300">→ {a.proposalCount} proposal{a.proposalCount !== 1 ? "s" : ""}</span>
                    {a.triggeredAt > 0 && <span className="text-slate-600 ml-auto">{new Date(a.triggeredAt).toLocaleTimeString()}</span>}
                  </div>
                ))}
              </div>
            )}

            {selfProposalData?.lastCycle && (
              <div className="text-xs text-slate-500 border-t border-slate-700 pt-2">
                Last self-proposal cycle: {selfProposalData.lastCycle.totalPassed}/{selfProposalData.lastCycle.totalProposals} proposals passed
                {selfProposalData.lastCycle.completedAt && ` — ${new Date(selfProposalData.lastCycle.completedAt).toLocaleString()}`}
              </div>
            )}
          </div>
        )}

        {!showPipelineFeed && (
          <button
            className="text-xs text-violet-400 hover:text-violet-300 flex items-center gap-1"
            onClick={() => setShowPipelineFeed(true)}
          >
            <Activity className="w-3 h-3" /> Show pipeline activity
          </button>
        )}

        {showNewForm && (
          <div className="bg-slate-900/50 border border-purple-500/30 rounded-lg p-4 space-y-3">
            <h3 className="text-sm font-medium text-purple-400">Submit New Proposal for 2/3 Vote</h3>
            <input
              type="text"
              value={newTitle}
              onChange={e => setNewTitle(e.target.value)}
              placeholder="Proposal title..."
              className="w-full bg-slate-800 border border-slate-600 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-purple-500"
              data-testid="input-proposal-title"
            />
            <textarea
              value={newDesc}
              onChange={e => setNewDesc(e.target.value)}
              placeholder="Describe the proposal for the 27-agent swarm to vote on..."
              className="w-full bg-slate-800 border border-slate-600 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-purple-500 min-h-[80px]"
              data-testid="input-proposal-description"
            />
            <div className="flex items-center gap-3">
              <select
                value={newCategory}
                onChange={e => setNewCategory(e.target.value)}
                className="bg-slate-800 border border-slate-600 rounded-lg px-3 py-2 text-sm"
                data-testid="select-proposal-category"
              >
                <option value="feature">Feature</option>
                <option value="security">Security</option>
                <option value="infrastructure">Infrastructure</option>
                <option value="governance">Governance</option>
                <option value="income">Income</option>
                <option value="community">Community</option>
              </select>
              <button
                className="bg-purple-500 text-white rounded-lg px-4 py-2 text-sm hover:bg-purple-600 transition disabled:opacity-50 flex items-center gap-1.5"
                onClick={() => {
                  if (newTitle.trim() && newDesc.trim()) {
                    createProposal.mutate({ title: newTitle, description: newDesc, category: newCategory });
                  }
                }}
                disabled={!newTitle.trim() || !newDesc.trim() || createProposal.isPending}
                data-testid="button-submit-proposal"
              >
                <Send className="w-4 h-4" />
                Submit for Vote
              </button>
            </div>
          </div>
        )}

        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs text-slate-500">Filter:</span>
          {(["all", "auto", "conference", "chat", "self-proposal", "manual"] as const).map(f => (
            <button
              key={f}
              className={`text-xs px-2.5 py-1 rounded-full border transition ${filterSource === f ? "bg-purple-500/20 text-purple-300 border-purple-500/40" : "text-slate-400 border-slate-700 hover:border-slate-500"}`}
              onClick={() => setFilterSource(f)}
            >
              {f === "all" ? `All (${allProposals.length})` : f === "auto" ? `Auto-Generated (${autoGeneratedCount})` : f.charAt(0).toUpperCase() + f.slice(1)}
            </button>
          ))}
        </div>

        <div className="space-y-3">
          {filteredProposals.map(proposal => {
            const expanded = expandedProposal === proposal.id;
            const approves = (proposal.votes || []).filter(v => v.vote === "approve").length;
            const rejects = (proposal.votes || []).filter(v => v.vote === "reject").length;
            const abstains = (proposal.votes || []).filter(v => v.vote === "abstain").length;
            const voters = (proposal.votes || []).filter(v => v.vote !== "abstain").length;
            const approvalRate = voters > 0 ? Math.round((approves / voters) * 100) : 0;
            const sourceInfo = proposal.source ? SOURCE_LABELS[proposal.source] : null;
            const isAutoGenerated = proposal.autoGenerated || (proposal.source && proposal.source !== "manual");

            return (
              <div
                key={proposal.id}
                className={`bg-slate-900/50 border rounded-lg overflow-hidden ${isAutoGenerated ? "border-violet-500/20" : "border-slate-700"}`}
                data-testid={`proposal-card-${proposal.id}`}
              >
                <div
                  className="p-4 cursor-pointer hover:bg-slate-800/30 transition"
                  onClick={() => setExpandedProposal(expanded ? null : proposal.id)}
                >
                  <div className="flex items-center gap-3">
                    {expanded ? <ChevronDown className="w-4 h-4 text-slate-500" /> : <ChevronRight className="w-4 h-4 text-slate-500" />}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-medium text-sm">{proposal.title}</span>
                        <Badge className={`${STATUS_COLORS[proposal.status]} text-[10px]`}>
                          {proposal.status === "approved" && <CheckCircle className="w-3 h-3 mr-1" />}
                          {proposal.status === "rejected" && <XCircle className="w-3 h-3 mr-1" />}
                          {proposal.status === "voting" && <Clock className="w-3 h-3 mr-1" />}
                          {proposal.status}
                        </Badge>
                        {isAutoGenerated && (
                          <Badge className="bg-violet-500/10 text-violet-400 border-violet-500/20 text-[10px] flex items-center gap-1">
                            <Zap className="w-2.5 h-2.5" />
                            Auto-Generated
                          </Badge>
                        )}
                        {sourceInfo && (
                          <Badge className={`${sourceInfo.color} text-[10px] flex items-center gap-1`}>
                            {sourceInfo.icon}
                            {sourceInfo.label}
                            {proposal.sourceId ? ` #${String(proposal.sourceId).slice(0, 6)}` : ""}
                          </Badge>
                        )}
                        <Badge className={`${CATEGORY_COLORS[proposal.category] ? `bg-${proposal.category === 'feature' ? 'blue' : proposal.category === 'security' ? 'red' : proposal.category === 'infrastructure' ? 'orange' : proposal.category === 'governance' ? 'purple' : proposal.category === 'income' ? 'green' : 'pink'}-500/10 border-${proposal.category === 'feature' ? 'blue' : proposal.category === 'security' ? 'red' : proposal.category === 'infrastructure' ? 'orange' : proposal.category === 'governance' ? 'purple' : proposal.category === 'income' ? 'green' : 'pink'}-500/20` : ''} ${CATEGORY_COLORS[proposal.category] || 'text-slate-400'} text-[10px]`}>
                          {proposal.category}
                        </Badge>
                        {proposal.executionStatus && proposal.executionStatus !== "pending" && (
                          <Badge className={`${EXEC_STATUS_COLORS[proposal.executionStatus]} bg-black/30 border-slate-600 text-[10px] flex items-center gap-1`}>
                            <RefreshCw className="w-2.5 h-2.5" />
                            {proposal.executionStatus}
                          </Badge>
                        )}
                      </div>
                      <div className="text-xs text-slate-500 mt-1">{proposal.description.slice(0, 120)}...</div>
                    </div>
                    <div className="shrink-0 text-right">
                      <div className="text-sm font-mono">{approvalRate}%</div>
                      <div className="text-[10px] text-slate-500">
                        <span className="text-green-400">{approves}✓</span> / <span className="text-red-400">{rejects}✗</span> / <span className="text-slate-400">{abstains}○</span>
                      </div>
                    </div>
                    <div className="w-16 shrink-0">
                      <Progress value={approvalRate} className="h-2" />
                      <div className="text-[10px] text-slate-500 text-center mt-0.5">2/3 = 67%</div>
                    </div>
                  </div>
                </div>

                {expanded && (
                  <div className="border-t border-slate-700 p-4 bg-slate-900/30 space-y-3">
                    <div className="text-xs text-slate-400 flex flex-wrap gap-4">
                      <span><span className="text-slate-500">Proposed by:</span> {proposal.proposedBy}</span>
                      <span><span className="text-slate-500">Created:</span> {new Date(proposal.createdAt).toLocaleString()}</span>
                      {proposal.source && (
                        <span><span className="text-slate-500">Source:</span> {proposal.source}{proposal.sourceId ? ` (#${proposal.sourceId})` : ""}</span>
                      )}
                      {proposal.actionRegistryId && (
                        <span><span className="text-slate-500">Registry:</span> <span className="text-yellow-400">{proposal.actionRegistryId}</span></span>
                      )}
                    </div>
                    {proposal.implementationNotes && (
                      <div className="text-xs text-slate-300 bg-black/30 rounded p-2">
                        {proposal.implementationNotes}
                      </div>
                    )}
                    {proposal.status === "approved" && (
                      <div className={`text-xs rounded p-2 border flex items-center gap-2 ${proposal.executionStatus === "queued" ? "bg-yellow-500/5 border-yellow-500/20 text-yellow-400" : proposal.executionStatus === "executed" ? "bg-green-500/5 border-green-500/20 text-green-400" : "bg-slate-800/30 border-slate-600 text-slate-400"}`}>
                        <RefreshCw className="w-3 h-3 shrink-0" />
                        {proposal.executionStatus === "queued"
                          ? `Queued for execution in Action Registry${proposal.actionRegistryId ? ` (${proposal.actionRegistryId})` : ""}`
                          : proposal.executionStatus === "executed"
                          ? "Implementation complete"
                          : "Approved — pending auto-queue"}
                      </div>
                    )}
                    <div className="text-xs text-slate-500 font-medium">Agent Votes ({(proposal.votes || []).length}/27):</div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-2 max-h-80 overflow-y-auto">
                      {(proposal.votes || []).map(vote => (
                        <div
                          key={vote.agentId}
                          className={`rounded p-2 border text-xs ${vote.vote === "approve" ? "border-green-500/20 bg-green-500/5" : vote.vote === "reject" ? "border-red-500/20 bg-red-500/5" : "border-slate-600 bg-slate-800/30"}`}
                          data-testid={`vote-${vote.agentId}`}
                        >
                          <div className="flex items-center justify-between">
                            <span className="font-medium flex items-center gap-1">
                              <Users className="w-3 h-3" />
                              {vote.agentName}
                            </span>
                            <span className={`font-mono ${vote.vote === "approve" ? "text-green-400" : vote.vote === "reject" ? "text-red-400" : "text-slate-400"}`}>
                              {vote.vote === "approve" ? "✓ APPROVE" : vote.vote === "reject" ? "✗ REJECT" : "○ ABSTAIN"}
                            </span>
                          </div>
                          <div className="text-slate-400 mt-1">{vote.reasoning}</div>
                          <div className="text-slate-500 mt-1">Confidence: {Math.round(vote.confidence * 100)}%</div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            );
          })}

          {filteredProposals.length === 0 && (
            <div className="text-center text-slate-500 py-12">
              <Vote className="w-10 h-10 mx-auto mb-3 opacity-30" />
              <div className="text-sm">No proposals yet for this filter</div>
              <div className="text-xs mt-1">Proposals are auto-generated from conferences, chat conversations, and the self-proposal engine</div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
