import { useState, useEffect } from "react";
import { Lightbulb, TrendingUp, DollarSign, Star, ChevronDown, ChevronUp, Zap, Globe, Brain } from "lucide-react";
import { cn } from "@/lib/utils";
import { GlassCard, PageHeader } from "@/components/ui/sovereign";

interface Idea {
  id: string;
  title: string;
  description: string;
  category: string;
  revenue: string;
  difficulty: "easy" | "medium" | "hard";
  time: string;
  score: number;
  tags: string[];
  steps: string[];
}

const IDEAS: Idea[] = [
  {
    id: "i1", title: "Sovereign AI API Reseller", description: "Resell access to Tessera Intelligence API with custom branding and markup. White-label the sovereign intelligence stack for enterprise clients.", category: "SaaS", revenue: "$5K–$50K/mo", difficulty: "easy", time: "1–2 weeks", score: 94,
    tags: ["AI", "API", "Recurring"], steps: ["Get Tessera API key", "Set up billing with Stripe", "Create branded developer portal", "Launch on ProductHunt", "Onboard first 10 customers"],
  },
  {
    id: "i2", title: "Sovereign Knowledge Newsletter", description: "Weekly synthesized intelligence briefings for business leaders, investors, and sovereignty-minded individuals. Monetize via premium subscriptions.", category: "Content", revenue: "$2K–$20K/mo", difficulty: "easy", time: "3–5 days", score: 88,
    tags: ["Content", "Email", "Subscription"], steps: ["Pick a niche (AI, sovereign finance, etc.)", "Set up beehiiv or Substack", "Use Tessera to auto-generate research", "Grow to 1000 free subscribers", "Launch $49/month tier"],
  },
  {
    id: "i3", title: "Multi-Agent Workflow Agency", description: "Build and sell custom multi-agent automation workflows for businesses. Use Tessera's swarm intelligence to 10x client operations.", category: "Agency", revenue: "$10K–$100K/project", difficulty: "medium", time: "2–4 weeks", score: 91,
    tags: ["Agency", "Automation", "B2B"], steps: ["Define 3 core workflow templates", "Build case studies with Tessera", "Price at $5K–$25K per deployment", "Target mid-market companies", "Build recurring retainer model"],
  },
  {
    id: "i4", title: "TSRT Token Staking Service", description: "Offer managed staking and yield optimization for TSRT holders. Handle the complexity of multi-agent reward pools on behalf of clients.", category: "DeFi", revenue: "$3K–$30K/mo", difficulty: "medium", time: "2–3 weeks", score: 82,
    tags: ["DeFi", "TSRT", "Crypto"], steps: ["Set up custody infrastructure", "Build yield optimizer", "Charge 10–20% performance fee", "Launch with 5 beta stakers", "Scale via referral program"],
  },
  {
    id: "i5", title: "Sacred Geometry NFT Collection", description: "Mint 963 unique sacred geometry NFTs generated by Tessera's pattern engine. Each NFT grants access to exclusive sovereign intelligence reports.", category: "NFT", revenue: "$50K–$500K (one-time)", difficulty: "medium", time: "4–6 weeks", score: 78,
    tags: ["NFT", "Sacred", "Art"], steps: ["Generate 963 unique artworks", "Set up smart contract", "Build holders community", "Create exclusive perks", "Launch whitelist sale"],
  },
];

const DIFF_STYLES: Record<string, { text: string; bg: string }> = {
  easy: { text: "text-emerald-400", bg: "bg-emerald-500/10" },
  medium: { text: "text-amber-400", bg: "bg-amber-500/10" },
  hard: { text: "text-red-400", bg: "bg-red-500/10" },
};

function IdeaCard({ idea }: { idea: Idea }) {
  const [open, setOpen] = useState(false);
  const d = DIFF_STYLES[idea.difficulty];

  return (
    <GlassCard className="border border-white/[0.08] hover:border-white/15 transition-all">
      <button className="w-full text-left p-4" onClick={() => setOpen(!open)}>
        <div className="flex items-start gap-3">
          <div className="w-8 h-8 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center shrink-0">
            <Lightbulb size={14} className="text-amber-400" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-sm font-semibold text-white">{idea.title}</span>
              <span className={cn("text-[9px] px-1.5 py-0.5 rounded-full border font-mono capitalize", d.bg, d.text, "border-current")}>{idea.difficulty}</span>
            </div>
            <p className="text-xs text-slate-400 mt-1 leading-snug line-clamp-2">{idea.description}</p>
            <div className="flex items-center gap-3 mt-1.5 flex-wrap">
              <span className="text-xs font-bold font-mono text-emerald-400">{idea.revenue}</span>
              <span className="text-[10px] text-slate-500">·</span>
              <span className="text-[10px] text-slate-500 font-mono">{idea.time} to launch</span>
              <span className="text-[10px] text-slate-500">·</span>
              <span className="text-[10px] text-slate-600 font-mono">{idea.category}</span>
            </div>
          </div>
          <div className="text-right shrink-0">
            <div className="text-lg font-bold font-mono text-violet-400">{idea.score}</div>
            <div className="text-[9px] text-slate-600">score</div>
            {open ? <ChevronUp size={12} className="text-slate-500 mt-1 ml-auto" /> : <ChevronDown size={12} className="text-slate-500 mt-1 ml-auto" />}
          </div>
        </div>
      </button>
      {open && (
        <div className="px-4 pb-4 space-y-3 border-t border-white/5 pt-3">
          <div className="flex flex-wrap gap-1.5">
            {idea.tags.map(t => <span key={t} className="text-[9px] px-1.5 py-0.5 rounded-full bg-white/5 border border-white/10 text-slate-500 font-mono">{t}</span>)}
          </div>
          <div>
            <div className="text-[9px] text-slate-600 font-mono mb-2">EXECUTION STEPS</div>
            <div className="space-y-1.5">
              {idea.steps.map((step, i) => (
                <div key={i} className="flex items-start gap-2">
                  <span className="text-[9px] font-bold font-mono text-violet-400 mt-0.5 shrink-0">{i + 1}.</span>
                  <span className="text-xs text-slate-400">{step}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </GlassCard>
  );
}

export default function BusinessIdeasPage() {
  useEffect(() => { document.title = "Business Ideas | Tessera"; }, []);

  return (
    <div className="p-4 pb-20 max-w-3xl mx-auto space-y-5">
      <PageHeader icon={Lightbulb} title="Business Ideas" subtitle="Tessera-powered sovereign business opportunities with execution playbooks" iconColor="text-amber-400" />

      <div className="grid grid-cols-3 gap-3">
        {[
          { label: "Ideas", val: IDEAS.length, color: "amber" },
          { label: "Avg Score", val: Math.round(IDEAS.reduce((s, i) => s + i.score, 0) / IDEAS.length), color: "violet" },
          { label: "Easy to Launch", val: IDEAS.filter(i => i.difficulty === "easy").length, color: "emerald" },
        ].map(({ label, val, color }) => (
          <GlassCard key={label} className="p-3 text-center">
            <div className={cn("text-2xl font-bold font-mono", `text-${color}-400`)}>{val}</div>
            <div className="text-[9px] text-slate-500 font-mono mt-1">{label.toUpperCase()}</div>
          </GlassCard>
        ))}
      </div>

      <div className="space-y-3">
        {IDEAS.sort((a, b) => b.score - a.score).map(idea => <IdeaCard key={idea.id} idea={idea} />)}
      </div>
    </div>
  );
}
